#pragma once

#include <cstdint>
#include <string>

#include "engine/build_id.h"

// Turns a stable address-library ID into a live address in the running game.
//
// Far Cry 2 v1.03 ships as two PC builds with different Dunia.dll layouts, so
// FCSE cannot bake RVAs. Instead every address it needs has an ID, and a table
// generated by tools/FCSE/tools/addrlib maps that ID to the right RVA for
// whichever build is running. IDs are append-only and never renumbered, so an
// ID compiled into a plugin keeps resolving to the same function forever.
//
// The table lives in an RCDATA resource rather than a compiled-in array: it is
// delta+varint encoded to about a third of its raw size, and expanded once at
// startup. See tools/FCSE/tools/addrlib/README.md for the encoding and for how
// the mapping is verified.
//
// Use the names in address_symbols.h rather than raw integers - FCSE's own call
// sites should never contain a bare ID.
namespace FCSE {

class AddressLibrary {
public:
    // Decodes the embedded table and binds it to `build`. Safe to call more
    // than once; only the first call does work. Returns false (and logs why) if
    // the resource is missing or malformed, or the build is unsupported - in
    // which case every Resolve() returns 0 rather than a guess.
    static bool Init(HMODULE duniaModule, const BuildInfo& build);

    // Decode a table from memory instead of from this exe's resources, binding
    // it to `duniaBase`. Init() is this plus finding the resource; it is public
    // so the test suite can check the decoder against a table the generator
    // produced, which is the only way an encoder/decoder disagreement gets
    // caught before it becomes a wrong address in someone's game.
    static bool LoadFromMemory(const void* blob, size_t size, const BuildInfo& build,
                               uintptr_t duniaBase);

    // Drops the decoded table. Tests only - the loader binds once and keeps it.
    static void Reset();

    static bool Ready();

    // The RVA for `id` in the running build, or 0 if this build has no
    // counterpart for it. Callers must treat 0 as "feature unavailable"; it is
    // never a valid address.
    static uint32_t Rva(uint32_t id);

    // Live address for `id`, or 0. Adding a 0 RVA to the module base would
    // produce a pointer to the DOS header, which is exactly the kind of
    // plausible-but-wrong value that turns a missing address into a crash
    // somewhere else entirely, so absence is reported as 0 here too.
    static uintptr_t Address(uint32_t id);

    template <class Fn>
    static Fn Function(uint32_t id) {
        return reinterpret_cast<Fn>(Address(id));
    }

    static uint32_t Count();
    static const std::string& MappingVersion();

    // How many of `ids` resolved. Features use this to decide up front whether
    // they can run at all, rather than discovering a missing address halfway
    // through building a UI page.
    static bool ResolveAll(const uint32_t* ids, size_t count);
};

} // namespace FCSE
