// Generated by tools/FCSE/tools/addrlib - do not edit by hand.
//
// The engine addresses FCSE itself uses, named. Each value is an RVA in the
// reference build (fc2_103_uplay) - the same number you would see in
// Ghidra with that DLL open, which is the point: it can be pasted straight
// into a disassembler and checked, unlike an opaque id.
//
// Pass these to AddressLibrary::Address(), which translates a reference-build
// RVA into a live address on whichever build is running.
//
// mapping version : 1.0
// source          : tools/FCSE/tools/addrlib/names.csv

#pragma once

#include <cstdint>

namespace FCSE {
namespace Symbols {

constexpr uint32_t kAddBoolSetting = 0x00CDE0D0;  // func
constexpr uint32_t kAddButton = 0x00CDBB80;  // func
constexpr uint32_t kAddSliderSetting = 0x00CDDFF0;  // func
constexpr uint32_t kAddValueListSetting = 0x0081D660;  // func
constexpr uint32_t kBaseOptionPageDisplay = 0x0087ED50;  // func
constexpr uint32_t kBaseUpdate = 0x00108C10;  // func
constexpr uint32_t kDisplayConfig = 0x0032D910;  // func
constexpr uint32_t kEditBoxSetText = 0x00AB0220;  // func
constexpr uint32_t kElementSetVisible = 0x00AB13F0;  // func
constexpr uint32_t kEmptyStringProxy = 0x00FD42D1;  // data
constexpr uint32_t kEngineSingleton = 0x00FE3178;  // data
constexpr uint32_t kFileNameCtor = 0x005E8800;  // func
constexpr uint32_t kFileNameSetIdentifier = 0x005E8CE0;  // func
constexpr uint32_t kGamePageCtor = 0x0081E9C0;  // func
constexpr uint32_t kGetUserDataElement = 0x00A963A0;  // func
constexpr uint32_t kNoTextGlobal = 0x0164FCA0;  // data
constexpr uint32_t kOptionsMenu = 0x0081AEE0;  // func
constexpr uint32_t kPageSetSelected = 0x00AA5180;  // func
constexpr uint32_t kPageVtable = 0x00EAD9D8;  // data
constexpr uint32_t kReaderGetFileSize = 0x0061D3F0;  // func
constexpr uint32_t kReaderOpen = 0x0061D480;  // func
constexpr uint32_t kSwitchPage = 0x001D1990;  // func
constexpr uint32_t kTextBaseSetText = 0x0007D770;  // func
constexpr uint32_t kTimeBlock = 0x01606360;  // data
constexpr uint32_t kUiPageBaseInit = 0x00109410;  // func
constexpr uint32_t kUpdate = 0x0065AEA0;  // func
constexpr uint32_t kYesTextGlobal = 0x0164FCA4;  // data

} // namespace Symbols
} // namespace FCSE
