#pragma once

#include <cstdint>
#include <string>

#include "engine/build_id.h"

// Translates an address found in one Dunia.dll build into the live address of
// the same code in whichever build is running.
//
// Far Cry 2 v1.03 ships as two PC builds with different layouts, so FCSE cannot
// bake RVAs. A table generated by tools/FCSE/tools/addrlib pairs them up. The
// key is simply the RVA in one build - there is no separate id space, because
// both builds are frozen and an RVA is therefore already a permanent name for a
// function, and unlike an id it can be pasted into Ghidra and checked.
//
// The two builds are not a fixed distance apart: the offset between them takes
// 2,608 different values across the mapping, so this lookup is the only correct
// way to translate.
//
// The table lives in an RCDATA resource rather than a compiled-in array: it is
// delta+varint encoded to about a third of its raw size, and expanded once at
// startup. See tools/FCSE/tools/addrlib/README.md for the encoding and for how
// the mapping is verified.
//
// Use the names in address_symbols.h rather than raw hex - FCSE's own call sites
// should say what they are calling.
namespace FCSE {

class AddressLibrary {
public:
    // Decodes the embedded table and binds it to `build`. Safe to call more
    // than once; only the first call does work. Returns false (and logs why) if
    // the resource is missing or malformed, or the build is unsupported - in
    // which case every Resolve() returns 0 rather than a guess.
    static bool Init(HMODULE duniaModule, const BuildInfo& build);

    // Decode a table from memory instead of from this exe's resources, binding
    // it to `duniaBase`. Init() is this plus finding the resource; it is public
    // so the test suite can check the decoder against a table the generator
    // produced, which is the only way an encoder/decoder disagreement gets
    // caught before it becomes a wrong address in someone's game.
    static bool LoadFromMemory(const void* blob, size_t size, const BuildInfo& build,
                               uintptr_t duniaBase);

    // Drops the decoded table. Tests only - the loader binds once and keeps it.
    static void Reset();

    static bool Ready();

    // "Here is an address I confirmed in build X - give me the equivalent in
    // whatever is running." Returns 0 if that RVA is not in the mapping, or has
    // no counterpart on this build.
    //
    // 0 is never a valid address. Adding a 0 RVA to the module base would give
    // a pointer to the DOS header, which is exactly the plausible-but-wrong
    // value that turns a missing address into a crash somewhere else entirely,
    // so absence is reported as 0 rather than as a base-relative pointer.
    static uintptr_t AddressFrom(DuniaBuild sourceBuild, uint32_t rva);

    // The same, for a reference-build (fc2_103_uplay) RVA - which is what every
    // constant in address_symbols.h is, and what most Far Cry 2 addresses ever
    // written down are.
    static uintptr_t Address(uint32_t referenceRva);

    template <class Fn>
    static Fn Function(uint32_t referenceRva) {
        return reinterpret_cast<Fn>(Address(referenceRva));
    }

    // That address's RVA in a specific build, running or not; 0 if absent.
    static uint32_t RvaIn(DuniaBuild build, uint32_t referenceRva);

    static const std::string& MappingVersion();

    // Whether every one of `referenceRvas` resolves. Features use this to decide
    // up front whether they can run at all, rather than discovering a missing
    // address halfway through building a UI page.
    static bool ResolveAll(const uint32_t* referenceRvas, size_t count);
};

} // namespace FCSE
