// Generated by tools/FCSE/tools/addrlib - do not edit by hand.
//
// Named address-library IDs. FCSE's own code refers to addresses through
// these rather than through raw integers, so a future regeneration cannot
// silently repoint a call site: the name is the contract, the ID is an
// implementation detail, and both are produced from registry.csv together.
//
// mapping version : 1.0
// reference build : fc2_103_uplay

#pragma once

#include <cstdint>

namespace FCSE {
namespace Symbols {

// func 0x00CDE0D0 in fc2_103_uplay
constexpr uint32_t kAddBoolSetting = 52074;
// func 0x00CDBB80 in fc2_103_uplay
constexpr uint32_t kAddButton = 52001;
// func 0x00CDDFF0 in fc2_103_uplay
constexpr uint32_t kAddSliderSetting = 52072;
// func 0x0081D660 in fc2_103_uplay
constexpr uint32_t kAddValueListSetting = 33619;
// func 0x0087ED50 in fc2_103_uplay
constexpr uint32_t kBaseOptionPageDisplay = 34824;
// func 0x00108C10 in fc2_103_uplay
constexpr uint32_t kBaseUpdate = 4614;
// func 0x0032D910 in fc2_103_uplay
constexpr uint32_t kDisplayConfig = 14623;
// func 0x00AB0220 in fc2_103_uplay
constexpr uint32_t kEditBoxSetText = 43042;
// func 0x00AB13F0 in fc2_103_uplay
constexpr uint32_t kElementSetVisible = 43055;
// data 0x00FD42D1 in fc2_103_uplay
constexpr uint32_t kEmptyStringProxy = 80574;
// data 0x00FE3178 in fc2_103_uplay
constexpr uint32_t kEngineSingleton = 81510;
// func 0x005E8800 in fc2_103_uplay
constexpr uint32_t kFileNameCtor = 25439;
// func 0x005E8CE0 in fc2_103_uplay
constexpr uint32_t kFileNameSetIdentifier = 89351;
// func 0x0081E9C0 in fc2_103_uplay
constexpr uint32_t kGamePageCtor = 33624;
// func 0x00A963A0 in fc2_103_uplay
constexpr uint32_t kGetUserDataElement = 42393;
// data 0x0164FCA0 in fc2_103_uplay
constexpr uint32_t kNoTextGlobal = 87400;
// func 0x0081AEE0 in fc2_103_uplay
constexpr uint32_t kOptionsMenu = 33601;
// func 0x00AA5180 in fc2_103_uplay
constexpr uint32_t kPageSetSelected = 42799;
// data 0x00EAD9D8 in fc2_103_uplay
constexpr uint32_t kPageVtable = 68077;
// func 0x0061D3F0 in fc2_103_uplay
constexpr uint32_t kReaderGetFileSize = 89352;
// func 0x0061D480 in fc2_103_uplay
constexpr uint32_t kReaderOpen = 26229;
// func 0x001D1990 in fc2_103_uplay
constexpr uint32_t kSwitchPage = 7953;
// func 0x0007D770 in fc2_103_uplay
constexpr uint32_t kTextBaseSetText = 2436;
// data 0x01606360 in fc2_103_uplay
constexpr uint32_t kTimeBlock = 82943;
// func 0x00109410 in fc2_103_uplay
constexpr uint32_t kUiPageBaseInit = 4622;
// func 0x0065AEA0 in fc2_103_uplay
constexpr uint32_t kUpdate = 27455;
// data 0x0164FCA4 in fc2_103_uplay
constexpr uint32_t kYesTextGlobal = 87401;

} // namespace Symbols
} // namespace FCSE
