using System.Collections;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using JackAll.Tools.Format.Mgb;

namespace JackAll.App.FileHandlers.Mgb;

/// <summary>
/// The <c>.mgb</c> (Magma UI) editor: a tree of the whole package on the left, a generated property
/// grid for the selected record on the right, and structural operations across the top.
/// </summary>
/// <remarks>
/// Everything the format can express is reachable, without a bespoke form per widget type, because
/// two things do the heavy lifting: the property grid is generated by reflecting over the model
/// (see <see cref="MgbPropertyRow"/>), and the "Add" picker is populated from the engine's own
/// <c>Factory</c> dispatchers (see <see cref="MgbEdit"/>) so it offers exactly the classes that are
/// legal in the selected position and nothing else.
///
/// Saving reserialises the whole package rather than splicing bytes, so edits that change sizes -
/// adding an element, retyping a string, declaring a new class in the type table - are ordinary
/// operations rather than the impossible cases they were for the previous editor.
/// </remarks>
public partial class MgbFileHandler : UserControl
{
    private readonly string _fileName;
    private readonly Action<byte[]> _replaceContent;
    private MgbPackage? _package;
    private MgbNameLookup _names = new();
    private MgbTreeNode? _selected;
    private readonly List<MgbPropertyRow> _rows = [];
    private int _invalidRows;

    public MgbFileHandler(string fileName, byte[] content, Action<byte[]> replaceContent)
    {
        InitializeComponent();
        _fileName = fileName;
        _replaceContent = replaceContent;
        Load(content);
    }

    private void Load(byte[] content)
    {
        Tree.ItemsSource = null;
        Properties.ItemsSource = null;
        _rows.Clear();
        _invalidRows = 0;
        _selected = null;

        try
        {
            _package = MgbPackage.Read(content);
            _names = MgbNameLookup.For(_package);
            HeaderText.Text = $"{_fileName}\n{_package.Describe(content.Length)}";
            Tree.ItemsSource = new[] { MgbTreeNode.Build(_package, _names) };
            SetStatus(null, ok: true);
        }
        catch (Exception ex)
        {
            _package = null;
            HeaderText.Text = $"{_fileName}\n\nCouldn't read this file: {ex.Message}";
            SetStatus(ex.Message, ok: false);
        }
        UpdateCommandStates();
    }

    private void Tree_SelectedItemChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
    {
        _selected = e.NewValue as MgbTreeNode;
        foreach (MgbPropertyRow row in _rows)
        {
            row.ValidityChanged -= OnRowValidityChanged;
        }
        _rows.Clear();
        _invalidRows = 0;

        _rows.AddRange(MgbPropertyRow.For(_selected?.Target));
        foreach (MgbPropertyRow row in _rows)
        {
            row.ValidityChanged += OnRowValidityChanged;
        }

        SelectionText.Text = _selected is null
            ? string.Empty
            : $"{_selected.Label}   ({_rows.Count} field(s))";
        Properties.ItemsSource = _rows;
        UpdateCommandStates();
    }

    private void OnRowValidityChanged(MgbPropertyRow row)
    {
        _invalidRows += row.IsValid ? -1 : 1;
        UpdateCommandStates();
        if (_invalidRows > 0)
        {
            SetStatus($"{_invalidRows} field(s) need fixing before this can be saved.", ok: false);
        }
        else
        {
            SetStatus(null, ok: true);
        }
    }

    // --- structural operations -------------------------------------------------------------

    private void AddButton_Click(object sender, RoutedEventArgs e)
    {
        if (_package is null)
        {
            return;
        }

        // What can legally be added depends only on where we are: the package's own area list takes
        // Factory::MakeArea's five classes, an area's element list takes Factory::MakeElement's
        // fourteen. Offering anything else would produce a file the engine dereferences a null for.
        (IReadOnlyList<string> choices, Func<string, object> create, IList list) = ResolveAddTarget();
        if (choices.Count == 0)
        {
            SetStatus("Select an area (to add an element) or the package (to add an area).", ok: false);
            return;
        }

        var menu = new ContextMenu();
        foreach (string choice in choices)
        {
            var item = new MenuItem { Header = choice };
            item.Click += (_, _) =>
            {
                try
                {
                    list.Add(create(choice));
                    Rebuild($"Added a {choice}.");
                }
                catch (Exception ex)
                {
                    SetStatus(ex.Message, ok: false);
                }
            };
            menu.Items.Add(item);
        }
        menu.PlacementTarget = AddButton;
        menu.IsOpen = true;
    }

    private (IReadOnlyList<string>, Func<string, object>, IList) ResolveAddTarget()
    {
        MgbPackage package = _package!;
        if (_selected?.Kind == MgbNodeKind.Area && _selected.Target is MgbArea area)
        {
            return (MgbEdit.LegalElementTypes,
                    name => MgbEdit.CreateElement(package, name, NewName(name)),
                    area.Elements);
        }
        if (_selected?.Kind is MgbNodeKind.Package or null || _selected?.Target is MgbPackage)
        {
            return (MgbEdit.LegalAreaTypes,
                    name => MgbEdit.CreateArea(package, name, NewName(name)),
                    package.Areas);
        }
        if (_selected?.Kind == MgbNodeKind.Element && _selected.OwnerList is { } owner)
        {
            // Adding while an element is selected appends a sibling - the same list, one level up.
            return (MgbEdit.LegalElementTypes,
                    name => MgbEdit.CreateElement(package, name, NewName(name)),
                    owner);
        }
        return ([], _ => throw new InvalidOperationException(), Array.Empty<object>());
    }

    /// <summary>Names are stored as hashes, so a new object needs one. A timestamped default keeps
    /// additions distinct; it is editable in the grid afterwards.</summary>
    private static string NewName(string typeName)
        => $"{typeName}_{DateTime.Now:HHmmssfff}";

    private void DuplicateButton_Click(object sender, RoutedEventArgs e)
    {
        if (_package is null || _selected?.OwnerList is not { } list)
        {
            return;
        }
        try
        {
            switch (_selected.Target)
            {
                case MgbArea area:
                    list.Insert(list.IndexOf(area) + 1, MgbEdit.DuplicateArea(_package, area));
                    break;
                case MgbElement element:
                    list.Insert(list.IndexOf(element) + 1, MgbEdit.DuplicateElement(_package, element));
                    break;
                default:
                    return;
            }
            Rebuild("Duplicated.");
        }
        catch (Exception ex)
        {
            SetStatus(ex.Message, ok: false);
        }
    }

    private void DeleteButton_Click(object sender, RoutedEventArgs e)
    {
        if (_selected?.OwnerList is not { } list || _selected.Target is null)
        {
            return;
        }
        list.Remove(_selected.Target);
        Rebuild("Deleted.");
    }

    private void MoveUpButton_Click(object sender, RoutedEventArgs e) => Move(-1);
    private void MoveDownButton_Click(object sender, RoutedEventArgs e) => Move(+1);

    private void Move(int delta)
    {
        if (_selected?.OwnerList is not { } list || _selected.Target is null)
        {
            return;
        }
        int from = list.IndexOf(_selected.Target);
        int to = from + delta;
        if (from < 0 || to < 0 || to >= list.Count)
        {
            return;
        }
        object item = _selected.Target;
        list.RemoveAt(from);
        list.Insert(to, item);
        Rebuild(delta < 0 ? "Moved up." : "Moved down.");
    }

    private void SaveButton_Click(object sender, RoutedEventArgs e)
    {
        if (_package is null)
        {
            return;
        }
        if (_invalidRows > 0)
        {
            SetStatus($"{_invalidRows} field(s) need fixing first.", ok: false);
            return;
        }
        try
        {
            byte[] bytes = _package.Write();
            _replaceContent(bytes);
            Load(bytes);
            SetStatus($"Saved - {bytes.Length:N0} bytes.", ok: true);
        }
        catch (Exception ex)
        {
            SetStatus($"Couldn't write this package: {ex.Message}", ok: false);
        }
    }

    private void Rebuild(string message)
    {
        if (_package is null)
        {
            return;
        }
        Tree.ItemsSource = new[] { MgbTreeNode.Build(_package, _names) };
        Properties.ItemsSource = null;
        _rows.Clear();
        _invalidRows = 0;
        _selected = null;
        SelectionText.Text = string.Empty;
        SetStatus(message + " Not written to the file until you press Save.", ok: true);
        UpdateCommandStates();
    }

    private void UpdateCommandStates()
    {
        bool loaded = _package is not null;
        bool listMember = _selected?.OwnerList is not null && _selected.Target is not null;
        AddButton.IsEnabled = loaded;
        DuplicateButton.IsEnabled = loaded && listMember;
        DeleteButton.IsEnabled = loaded && listMember;
        MoveUpButton.IsEnabled = loaded && listMember;
        MoveDownButton.IsEnabled = loaded && listMember;
        SaveButton.IsEnabled = loaded && _invalidRows == 0;
    }

    private void SetStatus(string? message, bool ok)
    {
        StatusText.Text = message ?? string.Empty;
        StatusText.Foreground = ok ? Brushes.DarkGreen : Brushes.DarkRed;
    }
}
