using System.Collections;
using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using JackAll.Tools.Format.Mgb;

namespace JackAll.App.FileHandlers.Mgb;

/// <summary>
/// One editable field of whatever record the tree has selected.
/// </summary>
/// <remarks>
/// Rows are generated by reflecting over the model's public fields rather than hand-written per
/// type. That is what makes "full support" tractable: ~25 record types share one property grid, and
/// a field added to the codec shows up in the UI automatically instead of needing a matching UI
/// change that someone will forget.
///
/// The same validity discipline as JackAll.App/XmlEditor's FCB grid: a row parses on every
/// keystroke, keeps the last good value, and reports invalidity so Save can be gated - a package
/// must never be written from a half-typed number.
/// </remarks>
public sealed class MgbPropertyRow : INotifyPropertyChanged
{
    private readonly Func<object?> _get;
    private readonly Action<object?> _set;
    private string _text;
    private bool _isValid = true;
    private string? _error;

    private MgbPropertyRow(string name, MgbRowKind kind, Type valueType, Func<object?> get, Action<object?> set)
    {
        Name = name;
        Kind = kind;
        ValueType = valueType;
        _get = get;
        _set = set;
        _text = Format(get());
    }

    public string Name { get; }
    public MgbRowKind Kind { get; }
    public Type ValueType { get; }

    /// <summary>Raised when <see cref="IsValid"/> flips, so the host can keep a running count of
    /// bad rows rather than rescanning on every keystroke.</summary>
    public event Action<MgbPropertyRow>? ValidityChanged;

    public string Text
    {
        get => _text;
        set
        {
            if (_text == value)
            {
                return;
            }
            _text = value;
            Revalidate();
            OnPropertyChanged();
        }
    }

    public bool BoolValue
    {
        get => _get() is true;
        set
        {
            _set(value);
            OnPropertyChanged();
        }
    }

    public bool IsValid
    {
        get => _isValid;
        private set
        {
            if (_isValid == value)
            {
                return;
            }
            _isValid = value;
            OnPropertyChanged();
            ValidityChanged?.Invoke(this);
        }
    }

    public string? Error
    {
        get => _error;
        private set { _error = value; OnPropertyChanged(); }
    }

    public bool IsBool => Kind == MgbRowKind.Bool;
    public bool IsText => Kind != MgbRowKind.Bool && Kind != MgbRowKind.ReadOnly;
    public bool IsReadOnly => Kind == MgbRowKind.ReadOnly;

    /// <summary>Builds the grid for one record. Returns an empty list for a grouping row.</summary>
    public static List<MgbPropertyRow> For(object? target)
    {
        var rows = new List<MgbPropertyRow>();
        if (target is null)
        {
            return rows;
        }

        // Friendly string views first (Text, LabelText, TexturePath, ...): they are the editors a
        // person actually wants, and they write through to the raw byte[] the codec uses.
        foreach (PropertyInfo property in target.GetType()
                     .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(p => p.PropertyType == typeof(string) && p is { CanRead: true, CanWrite: true })
                     .OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            rows.Add(new MgbPropertyRow(
                property.Name, MgbRowKind.String, typeof(string),
                () => property.GetValue(target),
                v => property.SetValue(target, v)));
        }

        foreach (FieldInfo field in target.GetType()
                     .GetFields(BindingFlags.Public | BindingFlags.Instance))
        {
            AddFieldRows(rows, target, field);
        }
        return rows;
    }

    private static void AddFieldRows(List<MgbPropertyRow> rows, object target, FieldInfo field)
    {
        Type type = field.FieldType;

        if (type == typeof(bool))
        {
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.Bool, type,
                () => field.GetValue(target), v => field.SetValue(target, v)));
        }
        else if (type == typeof(byte) || type == typeof(ushort) || type == typeof(uint))
        {
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.Integer, type,
                () => field.GetValue(target), v => field.SetValue(target, v)));
        }
        else if (type == typeof(uint?))
        {
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.OptionalInteger, type,
                () => field.GetValue(target), v => field.SetValue(target, v)));
        }
        else if (type == typeof(uint[]) || type == typeof(ushort[]))
        {
            // Fixed-width numeric blocks (colours, timings, the static box) get one row per slot so
            // they stay individually editable.
            var array = (Array?)field.GetValue(target);
            for (int i = 0; i < (array?.Length ?? 0); i++)
            {
                int index = i;
                Type elementType = type.GetElementType()!;
                rows.Add(new MgbPropertyRow($"{field.Name}[{index}]", MgbRowKind.Integer, elementType,
                    () => ((Array)field.GetValue(target)!).GetValue(index),
                    v => ((Array)field.GetValue(target)!).SetValue(v, index)));
            }
        }
        else if (type == typeof(byte[]))
        {
            // Raw bytes are shown but not edited here; the friendly string properties above are the
            // supported way to change them, and a hex blob is not a useful edit surface.
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.ReadOnly, type,
                () => field.GetValue(target), _ => { }));
        }
        else if (type == typeof(string))
        {
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.String, type,
                () => field.GetValue(target), v => field.SetValue(target, v)));
        }
        else if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
        {
            var list = (IList?)field.GetValue(target);
            rows.Add(new MgbPropertyRow($"{field.Name} (count)", MgbRowKind.ReadOnly, type,
                () => list?.Count ?? 0, _ => { }));
        }
    }

    private void Revalidate()
    {
        try
        {
            object? parsed = Parse(_text);
            _set(parsed);
            Error = null;
            IsValid = true;
        }
        catch (Exception ex)
        {
            Error = ex.Message;
            IsValid = false;
        }
    }

    private object? Parse(string text)
    {
        string trimmed = text.Trim();
        if (Kind == MgbRowKind.String)
        {
            return text;
        }
        if (Kind == MgbRowKind.OptionalInteger)
        {
            if (trimmed.Length == 0 || trimmed.Equals("none", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }
            return (uint?)ParseUnsigned(trimmed, uint.MaxValue);
        }

        ulong max = ValueType == typeof(byte) ? byte.MaxValue
            : ValueType == typeof(ushort) ? ushort.MaxValue
            : uint.MaxValue;
        ulong value = ParseUnsigned(trimmed, max);
        return ValueType == typeof(byte) ? (byte)value
            : ValueType == typeof(ushort) ? (ushort)value
            : (uint)value;
    }

    private static ulong ParseUnsigned(string text, ulong max)
    {
        bool hex = text.StartsWith("0x", StringComparison.OrdinalIgnoreCase);
        string digits = hex ? text[2..] : text;
        bool ok = hex
            ? ulong.TryParse(digits, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ulong value)
            : ulong.TryParse(digits, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
        if (!ok)
        {
            throw new FormatException($"'{text}' is not a whole number (decimal, or 0x-prefixed hex).");
        }
        if (value > max)
        {
            throw new OverflowException($"value must be between 0 and {max}.");
        }
        return value;
    }

    private static string Format(object? value) => value switch
    {
        null => "none",
        bool b => b ? "true" : "false",
        byte[] bytes => bytes.Length == 0 ? "(empty)" : $"({bytes.Length:N0} bytes) {Preview(bytes)}",
        int i => i.ToString(CultureInfo.InvariantCulture),
        _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty,
    };

    private static string Preview(byte[] bytes)
    {
        string hex = Convert.ToHexString(bytes.AsSpan(0, Math.Min(16, bytes.Length)));
        return bytes.Length > 16 ? hex + "…" : hex;
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}

public enum MgbRowKind
{
    Integer,
    OptionalInteger,
    Bool,
    String,
    ReadOnly,
}
