using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using JackAll.Core.Format.Rml;
using JackAll.Tools.Mgb;
using Microsoft.Win32;

namespace JackAll.App.FileHandlers.Mgb;

/// <summary>
/// One <c>.mgb</c> (Magma UI) editor tab: a tree of the whole package on the left, a generated
/// property grid for the selected record on the right, and structural operations across the top.
/// </summary>
/// <remarks>
/// Everything the format can express is reachable, without a bespoke form per widget type, because
/// two things do the heavy lifting: the property grid is generated by reflecting over the model
/// (see <see cref="MgbPropertyRow"/>), and the "Add" picker is populated from the engine's own
/// <c>Factory</c> dispatchers (see <see cref="MgbEdit"/>) so it offers exactly the classes that are
/// legal in the selected position and nothing else.
///
/// Saving reserialises the whole package rather than splicing bytes, so edits that change sizes -
/// adding an element, retyping a string, declaring a new class in the type table - are ordinary
/// operations rather than the impossible cases they were for the previous editor.
///
/// This lives in its own tab rather than the Files tab's preview column (where
/// <see cref="FileHandlers.Mgb.MgbFilePreviewHandler"/> now just launches it) for the same reason the
/// fragment XML and Domino editors do: a tree plus a property grid plus a command bar needs real
/// room, and an editor with pending unsaved changes must not be thrown away by clicking the next row
/// in the file list.
/// </remarks>
public partial class MgbTabView : UserControl
{
    private readonly string _fileName;
    private readonly Action<byte[]> _replaceContent;
    private readonly MgbTextureResolver? _textures;
    private MgbPackage? _package;
    private MgbNameLookup _names = new();
    private MgbTreeNode? _selected;

    /// <summary>Replaced wholesale on every selection, never cleared and refilled - see
    /// <see cref="ShowProperties"/> for why that distinction is load-bearing.</summary>
    private List<MgbPropertyRow> _rows = [];
    private int _invalidRows;
    private bool _isDirty;

    /// <summary><paramref name="readByPath"/> is the merged filesystem, used to resolve a material's
    /// texture path to the <c>.xbt</c> it names so the grid can preview it. Null leaves those rows
    /// as plain text - every other part of the editor works without it.</summary>
    public MgbTabView(string fileName, byte[] content, Action<byte[]> replaceContent,
                      Func<string, byte[]?>? readByPath = null)
    {
        InitializeComponent();
        _fileName = fileName;
        _replaceContent = replaceContent;
        _textures = readByPath is null ? null : new MgbTextureResolver(readByPath);
        Load(content);
    }

    /// <summary>The tab title, which the host decorates with a "*" while <see cref="IsDirty"/>.</summary>
    public string Title => _fileName;

    /// <summary>Whether the in-memory package has edits that <see cref="Save"/> hasn't staged yet.
    /// Structural operations and property-grid edits both write straight into the model, so this is
    /// the only thing standing between an unnoticed tab close and losing them.</summary>
    public bool IsDirty
    {
        get => _isDirty;
        private set
        {
            if (_isDirty == value)
            {
                return;
            }
            _isDirty = value;
            DirtyChanged?.Invoke();
        }
    }

    public event Action? DirtyChanged;

    private void Load(byte[] content)
    {
        Tree.ItemsSource = null;
        ShowProperties(null);
        _selected = null;

        try
        {
            _package = MgbPackage.Read(content);
            _names = MgbNameLookup.For(_package);
            HeaderText.Text = $"{_fileName}\n{_package.Describe(content.Length)}";
            Tree.ItemsSource = new[] { MgbTreeNode.Build(_package, _names) };
            SetStatus(null, ok: true);
        }
        catch (Exception ex)
        {
            _package = null;
            HeaderText.Text = $"{_fileName}\n\nCouldn't read this file: {ex.Message}";
            SetStatus(ex.Message, ok: false);
        }
        IsDirty = false;
        UpdateCommandStates();
    }

    private void Tree_SelectedItemChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
    {
        _selected = e.NewValue as MgbTreeNode;
        ShowProperties(_selected?.Target);

        SelectionText.Text = _selected is null
            ? string.Empty
            : $"{_selected.Label}   ({_rows.Count} field(s))";
        UpdateCommandStates();
    }

    /// <summary>
    /// Points the property grid at <paramref name="target"/>'s fields, moving the row subscriptions
    /// across with it.
    /// </summary>
    /// <remarks>
    /// The new rows go into a *fresh* list every time, deliberately. <see cref="ItemsControl.ItemsSource"/>
    /// is a dependency property, so assigning it the same <see cref="List{T}"/> instance again is a
    /// no-op - and a plain List raises no collection-changed notification either. Clearing and
    /// refilling one long-lived list therefore left the grid showing the first selection's rows
    /// forever, no matter what was clicked afterwards.
    /// </remarks>
    private void ShowProperties(object? target)
    {
        foreach (MgbPropertyRow row in _rows)
        {
            row.ValidityChanged -= OnRowValidityChanged;
            row.PropertyChanged -= OnRowEdited;
        }

        // Rows never write a value they failed to parse, so the outgoing selection's invalid ones
        // left nothing behind in the model - the count (and the message about it) go with them.
        bool hadInvalidRows = _invalidRows > 0;
        _invalidRows = 0;

        _rows = MgbPropertyRow.For(target, new MgbRowContext
        {
            ResolveTexture = _textures is null ? null : _textures.Resolve,
            ResolveOasis = OasisStringTable.Resolve,
        });
        foreach (MgbPropertyRow row in _rows)
        {
            row.ValidityChanged += OnRowValidityChanged;
            row.PropertyChanged += OnRowEdited;
        }

        Properties.ItemsSource = _rows;
        if (hadInvalidRows)
        {
            SetStatus(null, ok: true);
        }
    }

    private void OnRowValidityChanged(MgbPropertyRow row)
    {
        _invalidRows += row.IsValid ? -1 : 1;
        UpdateCommandStates();
        if (_invalidRows > 0)
        {
            SetStatus($"{_invalidRows} field(s) need fixing before this can be saved.", ok: false);
        }
        else
        {
            SetStatus(null, ok: true);
        }
    }

    /// <summary>A row writes through to the model as it is typed, so any change it reports is already
    /// a pending edit - no need to distinguish which property moved.</summary>
    private void OnRowEdited(object? sender, PropertyChangedEventArgs e) => IsDirty = true;

    // --- structural operations -------------------------------------------------------------

    private void AddButton_Click(object sender, RoutedEventArgs e)
    {
        if (_package is null)
        {
            return;
        }

        // What can legally be added depends only on where we are: the package's own area list takes
        // Factory::MakeArea's five classes, an area's element list takes Factory::MakeElement's
        // fourteen. Offering anything else would produce a file the engine dereferences a null for.
        (IReadOnlyList<string> choices, Func<string, object> create, IList list) = ResolveAddTarget();
        if (choices.Count == 0)
        {
            SetStatus("Select an area (to add an element) or the package (to add an area).", ok: false);
            return;
        }

        var menu = new ContextMenu();
        foreach (string choice in choices)
        {
            var item = new MenuItem { Header = choice };
            item.Click += (_, _) =>
            {
                try
                {
                    list.Add(create(choice));
                    Rebuild($"Added a {choice}.");
                }
                catch (Exception ex)
                {
                    SetStatus(ex.Message, ok: false);
                }
            };
            menu.Items.Add(item);
        }
        menu.PlacementTarget = AddButton;
        menu.IsOpen = true;
    }

    private (IReadOnlyList<string>, Func<string, object>, IList) ResolveAddTarget()
    {
        MgbPackage package = _package!;
        if (_selected?.Kind == MgbNodeKind.Area && _selected.Target is MgbArea area)
        {
            return (MgbEdit.LegalElementTypes,
                    name => MgbEdit.CreateElement(package, name, NewName(name)),
                    area.Elements);
        }
        if (_selected?.Kind is MgbNodeKind.Package or null || _selected?.Target is MgbPackage)
        {
            return (MgbEdit.LegalAreaTypes,
                    name => MgbEdit.CreateArea(package, name, NewName(name)),
                    package.Areas);
        }
        if (_selected?.Kind == MgbNodeKind.Element && _selected.OwnerList is { } owner)
        {
            // Adding while an element is selected appends a sibling - the same list, one level up.
            return (MgbEdit.LegalElementTypes,
                    name => MgbEdit.CreateElement(package, name, NewName(name)),
                    owner);
        }
        return ([], _ => throw new InvalidOperationException(), Array.Empty<object>());
    }

    /// <summary>Names are stored as hashes, so a new object needs one. A timestamped default keeps
    /// additions distinct; it is editable in the grid afterwards.</summary>
    private static string NewName(string typeName)
        => $"{typeName}_{DateTime.Now:HHmmssfff}";

    private void DuplicateButton_Click(object sender, RoutedEventArgs e)
    {
        if (_package is null || _selected?.OwnerList is not { } list)
        {
            return;
        }
        try
        {
            switch (_selected.Target)
            {
                case MgbArea area:
                    list.Insert(list.IndexOf(area) + 1, MgbEdit.DuplicateArea(_package, area));
                    break;
                case MgbElement element:
                    list.Insert(list.IndexOf(element) + 1, MgbEdit.DuplicateElement(_package, element));
                    break;
                default:
                    return;
            }
            Rebuild("Duplicated.");
        }
        catch (Exception ex)
        {
            SetStatus(ex.Message, ok: false);
        }
    }

    private void DeleteButton_Click(object sender, RoutedEventArgs e)
    {
        if (_selected?.OwnerList is not { } list || _selected.Target is null)
        {
            return;
        }
        list.Remove(_selected.Target);
        Rebuild("Deleted.");
    }

    private void MoveUpButton_Click(object sender, RoutedEventArgs e) => Move(-1);
    private void MoveDownButton_Click(object sender, RoutedEventArgs e) => Move(+1);

    private void Move(int delta)
    {
        if (_selected?.OwnerList is not { } list || _selected.Target is null)
        {
            return;
        }
        int from = list.IndexOf(_selected.Target);
        int to = from + delta;
        if (from < 0 || to < 0 || to >= list.Count)
        {
            return;
        }
        object item = _selected.Target;
        list.RemoveAt(from);
        list.Insert(to, item);
        Rebuild(delta < 0 ? "Moved up." : "Moved down.");
    }

    /// <summary>
    /// Writes the package out as XML for editing elsewhere.
    /// </summary>
    /// <remarks>
    /// An extra way in and out, not a replacement for the tree: the tab still edits the decoded
    /// model directly. XML earns its place for the things a tree is bad at - diffing two packages,
    /// reviewing a change, or a find-and-replace across hundreds of elements.
    /// </remarks>
    private void ExportXmlButton_Click(object sender, RoutedEventArgs e)
    {
        if (_package is null)
        {
            return;
        }

        var dialog = new SaveFileDialog
        {
            Title = "Export this package as XML…",
            FileName = Path.GetFileNameWithoutExtension(_fileName) + ".xml",
            Filter = "XML file|*.xml",
        };
        if (dialog.ShowDialog(Window.GetWindow(this)) != true)
        {
            return;
        }

        try
        {
            File.WriteAllText(dialog.FileName, MgbXml.ToXml(_package));
            SetStatus($"Exported to {dialog.FileName}", ok: true);
        }
        catch (Exception ex)
        {
            SetStatus($"Couldn't export: {ex.Message}", ok: false);
        }
    }

    /// <summary>Replaces the open package with one built from an XML document, leaving it staged as
    /// an unsaved edit so it can still be reviewed - or abandoned - before it touches the file.</summary>
    private void ImportXmlButton_Click(object sender, RoutedEventArgs e)
    {
        var dialog = new OpenFileDialog
        {
            Title = "Import a (possibly edited) exported .xml",
            Filter = "XML file|*.xml",
        };
        if (dialog.ShowDialog(Window.GetWindow(this)) != true)
        {
            return;
        }

        if (IsDirty && MessageBox.Show(
                Window.GetWindow(this),
                "This tab has unsaved changes. Importing replaces the whole package and discards them.\n\nContinue?",
                "JackAll", MessageBoxButton.OKCancel, MessageBoxImage.Warning) != MessageBoxResult.OK)
        {
            return;
        }

        MgbPackage imported;
        try
        {
            imported = MgbXml.FromXml(File.ReadAllText(dialog.FileName));
        }
        catch (Exception ex)
        {
            SetStatus($"Couldn't import: {ex.Message}", ok: false);
            return;
        }

        _package = imported;
        _names = MgbNameLookup.For(imported);
        Tree.ItemsSource = new[] { MgbTreeNode.Build(imported, _names) };
        ShowProperties(null);
        _selected = null;
        SelectionText.Text = string.Empty;
        IsDirty = true;
        UpdateCommandStates();
        SetStatus($"Imported {Path.GetFileName(dialog.FileName)}. Not written to the file until you press Save.",
            ok: true);
    }

    private void SaveButton_Click(object sender, RoutedEventArgs e)
    {
        if (Save() is { } error)
        {
            SetStatus(error, ok: false);
        }
    }

    /// <summary>Reserialises the package and stages it in the workspace, or returns why it couldn't -
    /// the same path the Save button and the host's close-with-unsaved-changes prompt both take.</summary>
    public string? Save()
    {
        if (_package is null)
        {
            return null;
        }
        if (_invalidRows > 0)
        {
            return $"{_invalidRows} field(s) need fixing first.";
        }
        try
        {
            byte[] bytes = _package.Write();
            _replaceContent(bytes);
            Load(bytes);
            SetStatus($"Saved - {bytes.Length:N0} bytes.", ok: true);
            return null;
        }
        catch (Exception ex)
        {
            return $"Couldn't write this package: {ex.Message}";
        }
    }

    private void Rebuild(string message)
    {
        if (_package is null)
        {
            return;
        }
        Tree.ItemsSource = new[] { MgbTreeNode.Build(_package, _names) };
        ShowProperties(null);
        _selected = null;
        SelectionText.Text = string.Empty;
        IsDirty = true;
        SetStatus(message + " Not written to the file until you press Save.", ok: true);
        UpdateCommandStates();
    }

    private void UpdateCommandStates()
    {
        bool loaded = _package is not null;
        bool listMember = _selected?.OwnerList is not null && _selected.Target is not null;
        AddButton.IsEnabled = loaded;
        DuplicateButton.IsEnabled = loaded && listMember;
        DeleteButton.IsEnabled = loaded && listMember;
        MoveUpButton.IsEnabled = loaded && listMember;
        MoveDownButton.IsEnabled = loaded && listMember;
        ExportXmlButton.IsEnabled = loaded;
        SaveButton.IsEnabled = loaded && _invalidRows == 0;
    }

    private void SetStatus(string? message, bool ok)
    {
        StatusText.Text = message ?? string.Empty;
        StatusText.Foreground = ok ? Brushes.DarkGreen : Brushes.DarkRed;
    }
}
