using System.Collections;
using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Windows.Media;
using JackAll.Tools.Format.Mgb;

namespace JackAll.App.Mgb;

/// <summary>
/// One editable field of whatever record the tree has selected.
/// </summary>
/// <remarks>
/// Rows are generated by reflecting over the model's public fields rather than hand-written per
/// type. That is what makes "full support" tractable: ~25 record types share one property grid, and
/// a field added to the codec shows up in the UI automatically instead of needing a matching UI
/// change that someone will forget.
///
/// What a field *means*, though, is not something reflection can see - the model stores floats as
/// <c>uint</c> bit patterns, colours as packed words, hashes as plain integers, and class names as
/// strings that are really closed enumerations. <see cref="KindOf"/> maps those from the field's own
/// name and type, so the grid shows a float editor, a colour swatch or a dropdown wherever one
/// belongs. The naming rules it keys off are the codec's own (see that method's remarks), not a
/// hand-kept list of special cases.
///
/// The same validity discipline as JackAll.App/XmlEditor's FCB grid: a row parses on every
/// keystroke, keeps the last good value, and reports invalidity so Save can be gated - a package
/// must never be written from a half-typed number.
/// </remarks>
public sealed class MgbPropertyRow : INotifyPropertyChanged
{
    private readonly Func<object?> _get;
    private readonly Action<object?> _set;
    private string _text;
    private bool _isValid = true;
    private string? _error;

    private MgbPropertyRow(string name, MgbRowKind kind, Type valueType, Func<object?> get, Action<object?> set)
    {
        Name = name;
        Kind = kind;
        ValueType = valueType;
        _get = get;
        _set = set;
        _text = Format(get(), kind);
    }

    public string Name { get; }
    public MgbRowKind Kind { get; }
    public Type ValueType { get; }

    /// <summary>The engine's name table for a <see cref="MgbRowKind.Enum"/> row. Null otherwise.</summary>
    private MgbEnum? Choice { get; init; }

    /// <summary>The names a <see cref="MgbRowKind.Enum"/> row picks from. Null otherwise.</summary>
    public IReadOnlyList<string>? Choices => Choice?.Names;

    /// <summary>Why a <see cref="MgbRowKind.ReadOnly"/> row can't be edited, for the tooltip. Null
    /// when there's nothing to explain (a plain byte blob).</summary>
    public string? Note { get; private init; }

    public bool HasNote => Note is not null;

    /// <summary>Raised when <see cref="IsValid"/> flips, so the host can keep a running count of
    /// bad rows rather than rescanning on every keystroke.</summary>
    public event Action<MgbPropertyRow>? ValidityChanged;

    public string Text
    {
        get => _text;
        set
        {
            if (_text == value)
            {
                return;
            }
            _text = value;
            Revalidate();
            OnPropertyChanged();
            if (Kind == MgbRowKind.Color)
            {
                RaiseColorChanged();
            }
            if (Kind == MgbRowKind.Enum)
            {
                OnPropertyChanged(nameof(SelectedChoice));
            }
        }
    }

    /// <summary>
    /// The name for the stored value, for the dropdown to select. Null when the value falls outside
    /// the table, which is why the raw box sits next to the dropdown rather than behind it - a value
    /// the engine's own name table doesn't cover still has to be visible and editable. (Several
    /// fields default to exactly such a value: a neighbour's <c>DIRECTION</c> defaults to 4 where the
    /// table only names 0-3.)
    /// </summary>
    public string? SelectedChoice
    {
        get => Choice is { } choice && CurrentValue() is { } value ? choice.NameFor(value) : null;
        set
        {
            if (value is not null && Choice is { } choice && choice.TryValueFor(value, out uint raw))
            {
                Text = raw.ToString(CultureInfo.InvariantCulture);
            }
        }
    }

    /// <summary>The stored value as a plain number, whatever width the field is. An enum-valued
    /// field is a <c>uint</c> in most records, a <c>byte</c> in a couple (a list box's
    /// <c>HEADERFOOTERPOS</c>) and a single <c>bool</c> in one (a slider's <c>ORIENTATION</c>).</summary>
    private uint? CurrentValue() => _get() switch
    {
        uint value => value,
        ushort value => value,
        byte value => value,
        bool value => value ? 1u : 0u,
        _ => null,
    };

    public bool BoolValue
    {
        get => _get() is true;
        set
        {
            _set(value);
            OnPropertyChanged();
        }
    }

    public bool IsValid
    {
        get => _isValid;
        private set
        {
            if (_isValid == value)
            {
                return;
            }
            _isValid = value;
            OnPropertyChanged();
            ValidityChanged?.Invoke(this);
        }
    }

    public string? Error
    {
        get => _error;
        private set { _error = value; OnPropertyChanged(); }
    }

    public bool IsBool => Kind == MgbRowKind.Bool;
    public bool IsReadOnly => Kind == MgbRowKind.ReadOnly;
    public bool IsColor => Kind == MgbRowKind.Color;
    public bool IsEnum => Kind == MgbRowKind.Enum;

    // --- colour channels -----------------------------------------------------------------------
    // Bound by the swatch popup's four sliders. Each writes back through Text so the hex box, the
    // swatch and the model all stay in step with one code path.

    public byte ColorA
    {
        get => MgbColor.Alpha(RawColor);
        set => SetChannel(MgbColor.Pack(value, ColorR, ColorG, ColorB));
    }

    public byte ColorR
    {
        get => MgbColor.Red(RawColor);
        set => SetChannel(MgbColor.Pack(ColorA, value, ColorG, ColorB));
    }

    public byte ColorG
    {
        get => MgbColor.Green(RawColor);
        set => SetChannel(MgbColor.Pack(ColorA, ColorR, value, ColorB));
    }

    public byte ColorB
    {
        get => MgbColor.Blue(RawColor);
        set => SetChannel(MgbColor.Pack(ColorA, ColorR, ColorG, value));
    }

    /// <summary>The colour itself, for the swatch. Drawn over a checkerboard in the template, so a
    /// low-alpha value reads as translucent rather than as an arbitrary flat colour.</summary>
    public Brush ColorBrush
    {
        get
        {
            uint value = RawColor;
            var brush = new SolidColorBrush(Color.FromArgb(
                MgbColor.Alpha(value), MgbColor.Red(value), MgbColor.Green(value), MgbColor.Blue(value)));
            brush.Freeze();
            return brush;
        }
    }

    /// <summary>The authored <c>A R G B</c> spelling, shown next to the swatch.</summary>
    public string ColorDescription => MgbColor.Describe(RawColor);

    private uint RawColor => _get() is uint value ? value : 0;

    private void SetChannel(uint packed)
    {
        Text = $"0x{packed:X8}";
    }

    private void RaiseColorChanged()
    {
        OnPropertyChanged(nameof(ColorA));
        OnPropertyChanged(nameof(ColorR));
        OnPropertyChanged(nameof(ColorG));
        OnPropertyChanged(nameof(ColorB));
        OnPropertyChanged(nameof(ColorBrush));
        OnPropertyChanged(nameof(ColorDescription));
    }

    // --- resolved extras shown under the editor -------------------------------------------------

    /// <summary>The localised string this row's value names, when it names one. Null - and the label
    /// stays hidden - for the ordinary case of a value that isn't an oasis id.</summary>
    public string? ResolvedText { get; private set; }

    public bool HasResolvedText => ResolvedText is not null;

    /// <summary>The texture a material's path points at, decoded. Null when the row isn't a texture
    /// path, or nothing in the merged filesystem provides it.</summary>
    public ImageSource? TextureImage { get; private set; }

    public bool HasTextureImage => TextureImage is not null;

    /// <summary>Where <see cref="TextureImage"/> was looked for, shown under a texture path whether
    /// or not it resolved - the archive path is not obvious from the authored one.</summary>
    public string? TexturePathNote { get; private set; }

    public bool HasTexturePathNote => TexturePathNote is not null;

    private MgbRowContext? _context;

    private void RefreshResolved()
    {
        if (_context is null)
        {
            return;
        }

        if (Kind is MgbRowKind.String or MgbRowKind.Hex or MgbRowKind.Integer)
        {
            string? resolved = _context.ResolveOasis?.Invoke(_text);
            if (resolved != ResolvedText)
            {
                ResolvedText = resolved;
                OnPropertyChanged(nameof(ResolvedText));
                OnPropertyChanged(nameof(HasResolvedText));
            }
        }

        if (IsTexturePath)
        {
            TextureImage = _context.ResolveTexture?.Invoke(_text);
            TexturePathNote = _text.Length == 0 ? null : MgbTextureResolver.ToArchivePath(_text)
                + (TextureImage is null ? "  (not in the merged filesystem)" : string.Empty);
            OnPropertyChanged(nameof(TextureImage));
            OnPropertyChanged(nameof(HasTextureImage));
            OnPropertyChanged(nameof(TexturePathNote));
            OnPropertyChanged(nameof(HasTexturePathNote));
        }
    }

    private bool IsTexturePath { get; init; }

    /// <summary>Builds the grid for one record. Returns an empty list for a grouping row.</summary>
    public static List<MgbPropertyRow> For(object? target, MgbRowContext? context = null)
    {
        var rows = new List<MgbPropertyRow>();
        if (target is null)
        {
            return rows;
        }

        // Friendly string views first (Text, LabelText, TexturePath, ...): they are the editors a
        // person actually wants, and they write through to the raw byte[] the codec uses.
        foreach (PropertyInfo property in target.GetType()
                     .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(p => p.PropertyType == typeof(string) && p is { CanRead: true, CanWrite: true })
                     .OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            rows.Add(new MgbPropertyRow(
                property.Name, MgbRowKind.String, typeof(string),
                () => property.GetValue(target),
                v => property.SetValue(target, v))
            {
                IsTexturePath = property.Name == nameof(MgbMaterial.TexturePath),
            });
        }

        foreach (FieldInfo field in target.GetType()
                     .GetFields(BindingFlags.Public | BindingFlags.Instance))
        {
            AddFieldRows(rows, target, field);
        }

        foreach (MgbPropertyRow row in rows)
        {
            row._context = context;
            row.RefreshResolved();
        }
        return rows;
    }

    private static void AddFieldRows(List<MgbPropertyRow> rows, object target, FieldInfo field)
    {
        Type type = field.FieldType;

        if (type == typeof(bool))
        {
            // A bool that the XML loader authors by name (a slider's ORIENTATION) reads far better
            // as its two names than as a checkbox captioned with the field name.
            rows.Add(new MgbPropertyRow(field.Name, ChoicesFor(field.Name) is null ? MgbRowKind.Bool : MgbRowKind.Enum,
                type, () => field.GetValue(target), v => field.SetValue(target, v))
            {
                Choice = ChoicesFor(field.Name),
            });
        }
        else if (type == typeof(byte) || type == typeof(ushort) || type == typeof(uint))
        {
            rows.Add(new MgbPropertyRow(field.Name, KindOf(field.Name, type), type,
                () => field.GetValue(target), v => field.SetValue(target, v))
            {
                Choice = ChoicesFor(field.Name),
            });
        }
        else if (type == typeof(uint?))
        {
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.OptionalInteger, type,
                () => field.GetValue(target), v => field.SetValue(target, v)));
        }
        else if (type == typeof(uint[]) || type == typeof(ushort[]))
        {
            // Fixed-width numeric blocks (colours, timings, the static box) get one row per slot so
            // they stay individually editable. The slot rows inherit the block's own kind, so
            // COLOR1..COLOR4 are four colour pickers and the four region floats are four floats.
            var array = (Array?)field.GetValue(target);
            Type elementType = type.GetElementType()!;
            MgbRowKind kind = KindOf(field.Name, elementType);
            for (int i = 0; i < (array?.Length ?? 0); i++)
            {
                int index = i;
                rows.Add(new MgbPropertyRow($"{field.Name}[{index}]", kind, elementType,
                    () => ((Array)field.GetValue(target)!).GetValue(index),
                    v => ((Array)field.GetValue(target)!).SetValue(v, index)));
            }
        }
        else if (type == typeof(byte[]))
        {
            // Raw bytes are shown but not edited here; the friendly string properties above are the
            // supported way to change them, and a hex blob is not a useful edit surface.
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.ReadOnly, type,
                () => field.GetValue(target), _ => { }));
        }
        else if (type == typeof(string))
        {
            if (ClassNameNote(target, field.Name) is { } note)
            {
                rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.ReadOnly, type,
                    () => field.GetValue(target), _ => { })
                {
                    Note = note,
                });
                return;
            }
            rows.Add(new MgbPropertyRow(field.Name, MgbRowKind.String, type,
                () => field.GetValue(target), v => field.SetValue(target, v)));
        }
        else if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
        {
            var list = (IList?)field.GetValue(target);
            rows.Add(new MgbPropertyRow($"{field.Name} (count)", MgbRowKind.ReadOnly, type,
                () => list?.Count ?? 0, _ => { }));
        }
    }

    /// <summary>
    /// Why a class-name field is shown read-only, or null for an ordinary string field.
    /// </summary>
    /// <remarks>
    /// A record's class is fixed when it is created, because it is what fixes the record's data
    /// layout: it selects a type-table slot byte, decides which body the writer emits, and (for an
    /// element) which state class every keyframe uses. Assigning the name on its own changes none of
    /// that, so it would leave the slot naming the old class and the body written in the old shape -
    /// and because this format carries no lengths or sentinels, the engine doesn't reject such a
    /// file, it reinterprets everything after it. These were free text boxes, which is why they're
    /// now read-only rather than merely discouraged. Add a new record of the class you want instead.
    /// </remarks>
    private static string? ClassNameNote(object target, string fieldName) => (target, fieldName) switch
    {
        (MgbElement, nameof(MgbElement.WidgetTypeName)) =>
            "Fixed when the element is created - it decides the type-table slot, the widget body and "
            + "every keyframe's state class. Add a new element of the class you want instead.",
        (MgbArea, nameof(MgbArea.TypeName)) =>
            "Fixed when the area is created - it decides the type-table slot and which tail the area "
            + "writes (a Page's default-element tags, a Cursor's hotspot, a Button's timings). Add a "
            + "new area of the class you want instead.",
        (MgbKeyframe, nameof(MgbKeyframe.StateTypeName)) =>
            "Derived, not stored: Factory::MakeState picks the state class from the owning element's "
            + "widget class alone, and the writer resets this from it on save.",
        (MgbActionExecuter, nameof(MgbActionExecuter.TypeName)) =>
            "Stored on the owning ActionCaller's type slot, not here. Changing this name alone would "
            + "leave the slot naming the old class and add or drop the event tail with it.",
        _ => null,
    };

    /// <summary>
    /// The engine's own name table for a field the XML loader authors as a name rather than a
    /// number, or null for an ordinary integer.
    /// </summary>
    /// <remarks>
    /// Matched on the field name, which is safe because these are the authored names recovered from
    /// <c>LoadVisitor</c> and each is unique across the model. Note <c>Interpolation</c> is the
    /// keyframe's easing curve and is *not* the same field as <c>MgbState.InterpolationFlags</c>,
    /// which is a bitmask and stays a plain number.
    /// </remarks>
    private static MgbEnum? ChoicesFor(string fieldName) => fieldName switch
    {
        nameof(MgbKeyframe.Interpolation) => MgbEnums.Interpolation,
        nameof(MgbTextBase.AlignmentX) => MgbEnums.AlignmentX,
        nameof(MgbTextBase.AlignmentY) => MgbEnums.AlignmentY,
        // MgbListBox.HeaderFooterPos is deliberately absent even though tag group 6 exists for
        // HEADERFOOTERPOS: the shipped packages put values like 10, 14, 206, 236 and 248 in that
        // byte, which a two-entry table cannot be. The list box's field names were inferred from the
        // class's XML vocabulary rather than the per-field offset join (see
        // docs/docs/file-formats/mgb-field-names.md), so this byte is probably not that field at all.
        nameof(MgbSlider.Orientation) => MgbEnums.Orientation,
        nameof(MgbImage.BlendingMode) => MgbEnums.BlendingMode,
        nameof(MgbImage.AddressingModeU) or nameof(MgbImage.AddressingModeV) => MgbEnums.AddressingMode,
        nameof(MgbElement.MaskMode) => MgbEnums.MaskMode,
        _ => null,
    };

    /// <summary>
    /// What an integer field actually holds, from its name.
    /// </summary>
    /// <remarks>
    /// Each rule tracks a codec convention rather than a list of fields, so a field added later gets
    /// the right editor without this method changing:
    /// <list type="bullet">
    /// <item><c>*Bits</c> is exactly the set the codec reads through <c>IMgbCodec.F32Bits</c> - a
    /// float stored as its <c>uint</c> bit pattern (<c>RegionBits</c>, <c>RotationBits</c>,
    /// <c>Scale/Tiling/OffsetXBits</c>...).</item>
    /// <item><c>*Color</c>/<c>Colors[n]</c> is a packed <c>0xAARRGGBB</c> word - see
    /// <see cref="MgbColor"/> for how that was pinned down.</item>
    /// <item><c>NameId</c> and <c>ActionId</c> are CRC-32 hashes, which are only ever meaningful as
    /// hex - a hash printed in decimal matches nothing anyone can look up.</item>
    /// <item>a field <see cref="ChoicesFor"/> has the engine's name table for is an enumeration the
    /// XML loader authors by name.</item>
    /// </list>
    /// </remarks>
    private static MgbRowKind KindOf(string fieldName, Type valueType)
    {
        if (valueType == typeof(uint) && fieldName.EndsWith("Bits", StringComparison.Ordinal))
        {
            return MgbRowKind.Float;
        }
        if (valueType == typeof(uint) && fieldName.Contains("Color", StringComparison.Ordinal))
        {
            return MgbRowKind.Color;
        }
        if (fieldName is nameof(MgbUserData.NameId) or nameof(MgbAction.ActionId))
        {
            return MgbRowKind.Hex;
        }
        if (ChoicesFor(fieldName) is not null)
        {
            return MgbRowKind.Enum;
        }
        return MgbRowKind.Integer;
    }

    private void Revalidate()
    {
        try
        {
            object? parsed = Parse(_text);
            _set(parsed);
            Error = null;
            IsValid = true;
            RefreshResolved();
        }
        catch (Exception ex)
        {
            Error = ex.Message;
            IsValid = false;
        }
    }

    private object? Parse(string text)
    {
        string trimmed = text.Trim();
        if (Kind == MgbRowKind.String)
        {
            return text;
        }
        if (Kind == MgbRowKind.Float)
        {
            if (!float.TryParse(trimmed, NumberStyles.Float, CultureInfo.InvariantCulture, out float single))
            {
                throw new FormatException($"'{text}' is not a number.");
            }
            return BitConverter.SingleToUInt32Bits(single);
        }
        if (Kind == MgbRowKind.OptionalInteger)
        {
            if (trimmed.Length == 0 || trimmed.Equals("none", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }
            return (uint?)ParseUnsigned(trimmed, uint.MaxValue);
        }

        // A slider's ORIENTATION is a named pair stored in a single bool, so its raw box is 0/1.
        if (Kind == MgbRowKind.Enum && ValueType == typeof(bool))
        {
            return ParseUnsigned(trimmed, 1) != 0;
        }

        ulong max = ValueType == typeof(byte) ? byte.MaxValue
            : ValueType == typeof(ushort) ? ushort.MaxValue
            : uint.MaxValue;
        ulong value = ParseUnsigned(trimmed, max);

        // Separate returns, not a conditional chain. Each one boxes on its own into this method's
        // object? return type, so the runtime type reaching FieldInfo.SetValue is the field's own.
        // A `a ? (byte)v : b ? (ushort)v : (uint)v` chain instead takes a best common type of uint
        // and widens the narrow branches to it *before* boxing, so the setter is handed a boxed uint
        // and throws - which is what made every byte and ushort field in this grid silently
        // unwritable. Casting one branch to object doesn't fix it either: the nested conditional
        // still has a common type of its own.
        if (ValueType == typeof(byte))
        {
            return (byte)value;
        }
        if (ValueType == typeof(ushort))
        {
            return (ushort)value;
        }
        return (uint)value;
    }

    private static ulong ParseUnsigned(string text, ulong max)
    {
        bool hex = text.StartsWith("0x", StringComparison.OrdinalIgnoreCase);
        string digits = hex ? text[2..] : text;
        bool ok = hex
            ? ulong.TryParse(digits, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ulong value)
            : ulong.TryParse(digits, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
        if (!ok)
        {
            throw new FormatException($"'{text}' is not a whole number (decimal, or 0x-prefixed hex).");
        }
        if (value > max)
        {
            throw new OverflowException($"value must be between 0 and {max}.");
        }
        return value;
    }

    private static string Format(object? value, MgbRowKind kind) => (kind, value) switch
    {
        (_, null) => kind == MgbRowKind.String ? string.Empty : "none",
        // Round-trip ("R") rather than a fixed number of decimals: these are exact bit patterns, and
        // reformatting one to fewer digits would silently rewrite the field on the next keystroke.
        (MgbRowKind.Float, uint bits) => BitConverter.UInt32BitsToSingle(bits).ToString("R", CultureInfo.InvariantCulture),
        (MgbRowKind.Hex or MgbRowKind.Color, uint id) => $"0x{id:X8}",
        // Before the plain bool arm: an enum stored in a bool shows the number its name maps to.
        (MgbRowKind.Enum, bool b) => b ? "1" : "0",
        (_, bool b) => b ? "true" : "false",
        (_, byte[] bytes) => bytes.Length == 0 ? "(empty)" : $"({bytes.Length:N0} bytes) {Preview(bytes)}",
        (_, int i) => i.ToString(CultureInfo.InvariantCulture),
        _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty,
    };

    private static string Preview(byte[] bytes)
    {
        string hex = Convert.ToHexString(bytes.AsSpan(0, Math.Min(16, bytes.Length)));
        return bytes.Length > 16 ? hex + "…" : hex;
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}

/// <summary>The two lookups that turn a stored value into something legible: a localised string, and
/// a texture. Both optional - a grid built without them still edits every field, it just shows less
/// alongside.</summary>
public sealed class MgbRowContext
{
    public Func<string, ImageSource?>? ResolveTexture { get; init; }
    public Func<string, string?>? ResolveOasis { get; init; }
}

public enum MgbRowKind
{
    Integer,
    OptionalInteger,
    Bool,
    String,
    ReadOnly,

    /// <summary>A float stored as its <c>uint</c> bit pattern - every <c>*Bits</c> field.</summary>
    Float,

    /// <summary>A hash, shown as <c>0x########</c>.</summary>
    Hex,

    /// <summary>A packed <c>0xAARRGGBB</c> colour word.</summary>
    Color,

    /// <summary>An integer the XML loader authors by name, picked from
    /// <see cref="MgbPropertyRow.Choices"/> - the name's index is the stored value.</summary>
    Enum,
}
