// Tests for IniFile, the persistence layer under bin\fcse.ini (see src/settings_registry.h).
//
// Built as its own tiny console exe (target `ini_file_tests`) against the real src/ini_file.cpp -
// no stubs, no test framework, and no dependency on Dunia.dll, so it runs anywhere the project
// builds. Run it with `ctest` from the build directory, or just launch the exe.
//
// This layer earns direct tests because its failure mode is silent and destructive: it rewrites
// the player's whole config on every toggle, so a bug loses settings rather than crashing. Two of
// the cases below (the fixed-point check and the new-key placement check) were written after the
// behaviour they cover was actually wrong.
#include "ini_file.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <windows.h>

static int g_failures = 0;

static void Check(bool ok, const char* what) {
    std::printf("%s  %s\n", ok ? "[ ok ]" : "[FAIL]", what);
    if (!ok) {
        ++g_failures;
    }
}

static std::string ReadAll(const std::wstring& path) {
    HANDLE f = CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                           FILE_ATTRIBUTE_NORMAL, nullptr);
    if (f == INVALID_HANDLE_VALUE) {
        return "<missing>";
    }
    char buf[8192];
    DWORD read = 0;
    ReadFile(f, buf, sizeof(buf), &read, nullptr);
    CloseHandle(f);
    return std::string(buf, read);
}

int main() {
    const std::wstring path = L"ini_test_scratch.ini";
    DeleteFileW(path.c_str());

    // --- 1. Missing file is not an error, and IsEmpty reports a fresh document.
    {
        FCSE::IniFile ini;
        Check(ini.Load(path), "Load() of a missing file succeeds");
        Check(ini.IsEmpty(), "a missing file yields an empty document");
        Check(ini.Find("FCSE", "Dummy setting") == nullptr, "Find() on an empty document misses");

        ini.AddPreambleComment("generated by the test");
        ini.Set("FCSE", "Dummy setting", "false");
        ini.Set("example_plugin", "Toggle toRed", "true");
        Check(ini.Save(path), "Save() creates the file");
    }

    // --- 2. Values survive a round trip.
    {
        FCSE::IniFile ini;
        Check(ini.Load(path), "Load() of the written file succeeds");
        Check(!ini.IsEmpty(), "a written file is not empty");
        const std::string* dummy = ini.Find("FCSE", "Dummy setting");
        const std::string* toRed = ini.Find("example_plugin", "Toggle toRed");
        Check(dummy != nullptr && *dummy == "false", "[FCSE] Dummy setting round-trips as false");
        Check(toRed != nullptr && *toRed == "true", "[example_plugin] Toggle toRed round-trips");
        Check(ini.Find("example_plugin", "Dummy setting") == nullptr,
              "keys are scoped to their group (no cross-group leak)");
    }

    // --- 3. A group whose plugin isn't loaded this run must survive a rewrite. This is the
    //        property the whole order-preserving design exists for.
    {
        FCSE::IniFile ini;
        ini.Load(path);
        ini.Set("FCSE", "Dummy setting", "true"); // only FCSE registers this run
        Check(ini.Save(path), "Save() after touching one group succeeds");
    }
    {
        FCSE::IniFile ini;
        ini.Load(path);
        const std::string* toRed = ini.Find("example_plugin", "Toggle toRed");
        const std::string* dummy = ini.Find("FCSE", "Dummy setting");
        Check(toRed != nullptr && *toRed == "true",
              "an absent plugin's group survives a rewrite untouched");
        Check(dummy != nullptr && *dummy == "true", "an updated value is actually updated");
    }

    // --- 4. Hand-edited content: comments, blank lines, odd spacing, mixed case, LF-only endings.
    {
        const char* handEdited = "; my notes\n"
                                 "\n"
                                 "[example_plugin]\n"
                                 "; why this is on\n"
                                 "Toggle toRed=YES\n"
                                 "   Spaced Key   =   off   \n"
                                 "\n"
                                 "[ghost_plugin]\n"
                                 "Some setting = true\n";
        HANDLE f = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS,
                               FILE_ATTRIBUTE_NORMAL, nullptr);
        DWORD written = 0;
        WriteFile(f, handEdited, static_cast<DWORD>(std::strlen(handEdited)), &written, nullptr);
        CloseHandle(f);

        FCSE::IniFile ini;
        Check(ini.Load(path), "Load() of a hand-edited LF-only file succeeds");
        const std::string* toRed = ini.Find("example_plugin", "Toggle toRed");
        const std::string* spaced = ini.Find("example_plugin", "Spaced Key");
        Check(toRed != nullptr && *toRed == "YES", "value keeps its original case for the parser");
        Check(spaced != nullptr && *spaced == "off", "key and value are both trimmed");

        ini.Set("example_plugin", "Toggle toRed", "false");
        ini.Save(path);

        std::string text = ReadAll(path);
        Check(text.find("; my notes") != std::string::npos, "leading comment block is preserved");
        Check(text.find("; why this is on") != std::string::npos,
              "an in-group comment is preserved");
        Check(text.find("[ghost_plugin]") != std::string::npos,
              "an unknown group is preserved verbatim");
        Check(text.find("Toggle toRed = false") != std::string::npos,
              "the edited key is rewritten canonically");
        Check(text.find("YES") == std::string::npos, "the old value is gone, not duplicated");
        Check(text.find("Toggle toRed") == text.rfind("Toggle toRed"),
              "the edited key appears exactly once");

        std::printf("\n--- final file ---\n%s------------------\n\n", text.c_str());
    }

    // --- 5. A key added to an existing group lands in that group, not at the end of the file.
    {
        FCSE::IniFile ini;
        ini.Load(path);
        ini.Set("example_plugin", "Added later", "true");
        ini.Save(path);

        std::string text = ReadAll(path);
        size_t added = text.find("Added later");
        size_t ghost = text.find("[ghost_plugin]");
        Check(added != std::string::npos && ghost != std::string::npos && added < ghost,
              "a new key is appended inside its own group, not after the next one");
    }

    // --- 6. Repeated load/save must reach a fixed point. The whole file is rewritten on every
    //        toggle, so any content the writer synthesizes but the reader keeps would accumulate
    //        without bound over a play session.
    {
        std::string previous;
        for (int pass = 0; pass < 4; ++pass) {
            FCSE::IniFile ini;
            ini.Load(path);
            ini.Set("example_plugin", "Toggle toRed", "true"); // constant, so only structure varies
            ini.Save(path);

            std::string text = ReadAll(path);
            if (pass >= 1) {
                Check(text == previous, "load/save is a fixed point - the file is byte-stable");
            }
            previous = text;
        }
        std::printf("\n--- after 4 save cycles ---\n%s---------------------------\n\n",
                    previous.c_str());
    }

    DeleteFileW(path.c_str());
    std::printf("\n%s (%d failure(s))\n", g_failures == 0 ? "ALL PASSED" : "FAILURES", g_failures);
    return g_failures == 0 ? 0 : 1;
}
