// Tests for IniFile, the persistence layer under bin\fcse.ini (see src/api/settings_registry.h).
//
// Built against the real src/ini_file.cpp - no stubs, and no dependency on Dunia.dll, so it runs
// anywhere the project builds. Run with `ctest` from the build directory, or just launch the exe.
//
// This layer earns direct tests because its failure mode is silent and destructive: it rewrites
// the player's whole config on every toggle, so a bug loses settings rather than crashing. Two of
// the cases below (the fixed-point check and the new-key placement check) were written after the
// behaviour they cover was actually wrong.
#include "ini_file.h"

#include <gtest/gtest.h>

#include <cstring>
#include <string>
#include <windows.h>

namespace {

// Each test gets its own scratch file, named after itself, created empty and removed afterwards -
// so a case can be run alone, in any order, and a failure leaves a file whose name says which test
// wrote it (the run deletes it, but a crash or a debugger stop does not).
class IniFileTest : public ::testing::Test {
protected:
    void SetUp() override {
        const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
        std::string name = std::string("ini_test_") + info->name() + ".ini";
        path_.assign(name.begin(), name.end()); // ASCII test names only
        DeleteFileW(path_.c_str());
    }

    void TearDown() override { DeleteFileW(path_.c_str()); }

    // Drops `text` at the scratch path verbatim, for the cases that start from a hand-written file
    // rather than from something IniFile itself produced.
    void WriteAll(const char* text) const {
        HANDLE f = CreateFileW(path_.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS,
                               FILE_ATTRIBUTE_NORMAL, nullptr);
        ASSERT_NE(f, INVALID_HANDLE_VALUE);
        DWORD written = 0;
        WriteFile(f, text, static_cast<DWORD>(std::strlen(text)), &written, nullptr);
        CloseHandle(f);
    }

    // The file as bytes, for the assertions about what the writer actually laid down - the public
    // API can only report what the reader makes of it, and half of what this layer promises is
    // about the text itself.
    std::string ReadAll() const {
        HANDLE f = CreateFileW(path_.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                               FILE_ATTRIBUTE_NORMAL, nullptr);
        if (f == INVALID_HANDLE_VALUE) {
            return "<missing>";
        }
        char buf[8192];
        DWORD read = 0;
        ReadFile(f, buf, sizeof(buf), &read, nullptr);
        CloseHandle(f);
        return std::string(buf, read);
    }

    std::wstring path_;
};

// A first run has no file, and that is the normal case rather than an error.
TEST_F(IniFileTest, MissingFileLoadsAsAnEmptyDocument) {
    FCSE::IniFile ini;
    EXPECT_TRUE(ini.Load(path_)) << "Load() of a missing file should succeed";
    EXPECT_TRUE(ini.IsEmpty());
    EXPECT_EQ(ini.Find("FCSE", "Dummy setting"), nullptr);

    ini.AddPreambleComment("generated by the test");
    ini.Set("FCSE", "Dummy setting", "false");
    EXPECT_TRUE(ini.Save(path_));
    EXPECT_NE(ReadAll(), "<missing>");
}

TEST_F(IniFileTest, ValuesRoundTrip) {
    {
        FCSE::IniFile ini;
        ini.Load(path_);
        ini.Set("FCSE", "Dummy setting", "false");
        ini.Set("example_plugin", "Toggle toRed", "true");
        ASSERT_TRUE(ini.Save(path_));
    }

    FCSE::IniFile ini;
    ASSERT_TRUE(ini.Load(path_));
    EXPECT_FALSE(ini.IsEmpty());

    const std::string* dummy = ini.Find("FCSE", "Dummy setting");
    const std::string* toRed = ini.Find("example_plugin", "Toggle toRed");
    ASSERT_NE(dummy, nullptr);
    ASSERT_NE(toRed, nullptr);
    EXPECT_EQ(*dummy, "false");
    EXPECT_EQ(*toRed, "true");
    EXPECT_EQ(ini.Find("example_plugin", "Dummy setting"), nullptr)
        << "keys must be scoped to their group";
}

// The property the whole order-preserving design exists for: the file is the union of every plugin
// that has ever run, but a launch only sees the ones installed now.
TEST_F(IniFileTest, AbsentPluginsGroupSurvivesARewrite) {
    {
        FCSE::IniFile ini;
        ini.Load(path_);
        ini.Set("FCSE", "Dummy setting", "false");
        ini.Set("example_plugin", "Toggle toRed", "true");
        ASSERT_TRUE(ini.Save(path_));
    }
    {
        FCSE::IniFile ini;
        ini.Load(path_);
        ini.Set("FCSE", "Dummy setting", "true"); // only FCSE registers this run
        ASSERT_TRUE(ini.Save(path_));
    }

    FCSE::IniFile ini;
    ini.Load(path_);
    const std::string* toRed = ini.Find("example_plugin", "Toggle toRed");
    const std::string* dummy = ini.Find("FCSE", "Dummy setting");
    ASSERT_NE(toRed, nullptr) << "an untouched group must not be dropped by a rewrite";
    EXPECT_EQ(*toRed, "true");
    ASSERT_NE(dummy, nullptr);
    EXPECT_EQ(*dummy, "true") << "an updated value should actually be updated";
}

// Comments, blank lines, odd spacing, mixed case and LF-only endings all come from a player editing
// the file by hand, which is a supported way to configure a plugin.
TEST_F(IniFileTest, HandEditedContentIsPreserved) {
    WriteAll("; my notes\n"
             "\n"
             "[example_plugin]\n"
             "; why this is on\n"
             "Toggle toRed=YES\n"
             "   Spaced Key   =   off   \n"
             "\n"
             "[ghost_plugin]\n"
             "Some setting = true\n");

    FCSE::IniFile ini;
    ASSERT_TRUE(ini.Load(path_));
    const std::string* toRed = ini.Find("example_plugin", "Toggle toRed");
    const std::string* spaced = ini.Find("example_plugin", "Spaced Key");
    ASSERT_NE(toRed, nullptr);
    ASSERT_NE(spaced, nullptr);
    EXPECT_EQ(*toRed, "YES") << "a value keeps its original case for the parser";
    EXPECT_EQ(*spaced, "off") << "key and value are both trimmed";

    ini.Set("example_plugin", "Toggle toRed", "false");
    ASSERT_TRUE(ini.Save(path_));

    const std::string text = ReadAll();
    EXPECT_NE(text.find("; my notes"), std::string::npos) << "leading comment block is preserved";
    EXPECT_NE(text.find("; why this is on"), std::string::npos) << "in-group comment is preserved";
    EXPECT_NE(text.find("[ghost_plugin]"), std::string::npos)
        << "an unknown group is preserved verbatim";
    EXPECT_NE(text.find("Toggle toRed = false"), std::string::npos)
        << "the edited key is rewritten canonically";
    EXPECT_EQ(text.find("YES"), std::string::npos) << "the old value is gone, not duplicated";
    EXPECT_EQ(text.find("Toggle toRed"), text.rfind("Toggle toRed"))
        << "the edited key appears exactly once";
}

TEST_F(IniFileTest, NewKeyLandsInsideItsOwnGroup) {
    WriteAll("[example_plugin]\n"
             "Toggle toRed = false\n"
             "\n"
             "[ghost_plugin]\n"
             "Some setting = true\n");

    FCSE::IniFile ini;
    ASSERT_TRUE(ini.Load(path_));
    ini.Set("example_plugin", "Added later", "true");
    ASSERT_TRUE(ini.Save(path_));

    const std::string text = ReadAll();
    const size_t added = text.find("Added later");
    const size_t ghost = text.find("[ghost_plugin]");
    ASSERT_NE(added, std::string::npos);
    ASSERT_NE(ghost, std::string::npos);
    EXPECT_LT(added, ghost) << "a new key belongs in its own group, not after the next one";
}

// The whole file is rewritten on every toggle, so any content the writer synthesizes but the reader
// keeps would accumulate without bound over a play session.
TEST_F(IniFileTest, LoadSaveReachesAFixedPoint) {
    WriteAll("; my notes\n"
             "\n"
             "[example_plugin]\n"
             "; why this is on\n"
             "Toggle toRed = true\n"
             "\n"
             "[ghost_plugin]\n"
             "Some setting = true\n");

    std::string previous;
    for (int pass = 0; pass < 4; ++pass) {
        FCSE::IniFile ini;
        ini.Load(path_);
        ini.Set("example_plugin", "Toggle toRed", "true"); // constant, so only structure varies
        ASSERT_TRUE(ini.Save(path_));

        const std::string text = ReadAll();
        if (pass >= 1) {
            EXPECT_EQ(text, previous) << "load/save must be byte-stable, pass " << pass;
        }
        previous = text;
    }
}

} // namespace
