namespace JackAll.Tools.Ai;

/// <summary>One-line descriptions of the task classes a brain designer meets most.</summary>
public static class AiTaskHelp
{
    private static readonly Dictionary<string, string> Descriptions = new(StringComparer.Ordinal)
    {
        ["CPlan"] = "Starts the tasks wired to its start anchor and runs until one of its exits fires.",
        ["CBlueprintDecision"] = "A reusable sub-plan; its exits report which way the decision went.",
        ["CBrainMerc"] = "The soldier's top brain. C++ picks the behaviour (idle, alert, combat…) and runs the matching plan.",
        ["CBrainMercIdle"] = "Idle layer: patrols, smart-terrain activities and social reactions.",
        ["CBrainMercAlert"] = "Alert layer: searching, escaping grenades, reacting to snipers and corpses.",
        ["CBrainMercCombat"] = "Combat layer. C++ picks the range band - kill ≤12 m, short ≤25 m, medium ≤35 m, long ≤50 m - and special cases like grenades, rushes and flanking.",
        ["CBrainMercThreshold"] = "Wounded layer: the victim crawls and calls for help, a rescuer carries and heals him.",
        ["CBrainMercSpecial"] = "Special deaths and states: burning, drowning, falling.",
        ["CBrainMercSocial"] = "Social layer: reactions to a player walking among calm soldiers.",
        ["CBrainMercVehicle"] = "Vehicle layer: driving, gunning and chasing.",
        ["CTaskWait"] = "Waits the given time, then exits with success.",
        ["CTaskShoot"] = "Fires at the target. How often it hits is decided by the archetype's marksmanship, not here.",
        ["CTaskSetFireStrategy"] = "Sets how he fires - bursts, suppression, single shots.",
        ["CTaskSetAimStrategy"] = "Sets what he aims at while moving and shooting.",
        ["CTaskSetLookStrategy"] = "Sets where he looks.",
        ["CTaskSetPawnAttribute"] = "Sets stance, aiming and look-at flags. 2 leaves a flag unchanged.",
        ["CTaskSetPostureIntention"] = "Asks the animation system for a stance - stand, crouch, prone.",
        ["CTaskSetSpeed"] = "Sets the movement speed band.",
        ["CTaskPathFind"] = "Finds a path to a destination fact.",
        ["CTaskPathFollow"] = "Follows the found path.",
        ["CTaskPathFindAndMoveTo"] = "Finds a path and walks it in one task.",
        ["CTaskFindCover"] = "Looks for a cover point near him, against the target.",
        ["CTaskFindCoverAttack"] = "Looks for a cover point to attack from.",
        ["CTaskChooseCoverAttack"] = "Picks how to attack from cover - lean, pop up, blind fire.",
        ["CTaskCoverAttack"] = "Attacks from cover. Shipped only in the buddy brain.",
        ["CTaskFindLeapFrogStep"] = "Finds the next bound of a leap-frog advance while others cover.",
        ["CTaskComputeLeapFrogStep"] = "Computes the next leap-frog bound.",
        ["CTaskFindEscapePos"] = "Finds a place away from a threat - grenade, fire, vehicle.",
        ["CTaskFindRiskPoints"] = "Finds the directions an attack could come from.",
        ["CTaskSelectRiskPoint"] = "Picks one risk point to watch.",
        ["CTaskFindStrategicPoint"] = "Finds a strategic point to hold.",
        ["CTaskGetSniperPoint"] = "Finds a sniping position.",
        ["CTaskUseSniperPoint"] = "Takes up a sniping position.",
        ["CTaskFindMountedWeapon"] = "Looks for a free mounted gun.",
        ["CTaskUseMountedWeapon"] = "Mans a mounted gun.",
        ["CTaskSwitchWeapon"] = "Switches to another weapon.",
        ["CTaskSelectWeapon"] = "Picks the best weapon for the situation.",
        ["CTaskComputeProjectileTrajectory"] = "Computes a grenade throw.",
        ["CTaskEmitBark"] = "Says a line.",
        ["CTaskStopBark"] = "Stops a line.",
        ["CTaskFuzzyChoice"] = "Picks one of its exits at random, weighted.",
        ["CTaskCheckFactExist"] = "Branches on whether a blackboard fact is set.",
        ["CTaskUpdateBlackboard"] = "Writes a fact to his blackboard.",
        ["CTaskOperateOnFlagField"] = "Sets or clears blackboard flags.",
        ["CTaskSendActionSignal"] = "Signals another part of the brain.",
        ["CTaskCheckActionSignal"] = "Branches on a signal.",
        ["CTaskCheckIsInDistance"] = "Branches on a distance.",
        ["CTaskCheckTargetVisible"] = "Branches on whether he can see the target.",
        ["CTaskCheckUnderFire"] = "Branches on whether he is being shot at.",
        ["CTaskCheckDifficultyLevel"] = "Rolls an AdaptativeBehavior chance at the campaign progression level, not the difficulty setting.",
        ["CTaskCheckFireRange"] = "Branches on the range band.",
        ["CTaskCheckAmmoStatus"] = "Branches on ammunition left.",
        ["CTaskSelectBestTarget"] = "Picks the best target.",
        ["CTaskLookAround"] = "Scans around.",
        ["CTaskLookAt"] = "Looks at a point.",
        ["CTaskAimAt"] = "Aims at a point without firing.",
        ["CTaskUseAIBuilding"] = "Moves through a building's AI data - doors, windows.",
        ["CTaskGetBuildingEntry"] = "Finds a way into a building.",
        ["CTaskManageArmy"] = "Squad logic: roles and orders. Barely used in the shipped brains.",
        ["CTaskCheckSquadRole"] = "Branches on his squad role. Implemented but unused.",
        ["CTaskCheckSquadAction"] = "Branches on the squad's current order. Implemented but unused.",
        ["CTaskCheckVisibleByPlayer"] = "Branches on whether the player can see him. Implemented but unused.",
        ["CTaskFindProtectionPoint"] = "Finds a point protected from the target. Implemented but unused.",
        ["CScannerPawnSenses"] = "Sense: fires while its sensory condition holds.",
        ["CScannerFactExist"] = "Sense: fires when a blackboard fact appears.",
        ["CScannerIsInDistance"] = "Sense: fires when something comes within a distance.",
        ["CScannerTargetVisible"] = "Sense: fires when the target becomes visible or hidden.",
        ["CScannerIsUnderFire"] = "Sense: fires when bullets land near him.",
        ["CScannerNewTargetNeeded"] = "Sense: fires when he should pick a new target.",
        ["CScannerSideLookOpening"] = "Sense: fires when a side view opens up. Implemented but unused.",
    };

    public static string Describe(string cls) => Descriptions.GetValueOrDefault(cls, "");
}
