"""Stage F: emit the C++ address table FCSE compiles in.

IDs are dense from 0, so the table is a flat array indexed by ID: resolving an
address is a bounds check and one load, with no search and no runtime
allocation. Both supported builds get a column; an ID absent from a build holds
kRvaMissing so the resolver can fail cleanly instead of returning a plausible
wrong address.

Also writes mapping_manifest.json recording the two input binaries, the config
that produced the mapping, and the per-tier counts -- so a shipped table can
always be traced back to exactly what generated it.

    python emit.py [--config addrlib.toml]
"""

import argparse
import os
import sys
import time
from collections import defaultdict

import common

MISSING = 0xFFFFFFFF


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default=None)
    args = ap.parse_args()

    cfg = common.load_config(args.config)
    out = common.out_dir(cfg)
    reporter = common.Reporter("addrlib :: emit")

    registry = common.read_csv_rows(os.path.join(common.tool_dir(), "registry.csv"))
    if not registry:
        raise SystemExit("[!] registry.csv is empty - run mint_ids.py first")

    # reference rva -> target rva, from both maps
    target = {}
    tier_of = {}
    for r in common.read_csv_rows(os.path.join(out, "mapping.csv")):
        if r["tier"] in common.SHIPPING_TIERS:
            a = common.parse_rva(r["ref_rva"])
            target[a] = common.parse_rva(r["tgt_rva"])
            tier_of[a] = r["tier"]
    data_path = os.path.join(out, "data_map.jsonl")
    if os.path.exists(data_path):
        for r in common.read_jsonl(data_path):
            target.setdefault(r["ref_rva"], r["tgt_rva"])
            tier_of.setdefault(r["ref_rva"], common.TIER_NEAR_EXACT)

    ref_col, tgt_col = [], []
    missing = 0
    for row in sorted(registry, key=lambda r: int(r["id"])):
        rva = common.parse_rva(row["steam_rva"])
        ref_col.append(rva)
        t = target.get(rva)
        if t is None:
            tgt_col.append(MISSING)
            missing += 1
        else:
            tgt_col.append(t)

    count = len(ref_col)
    ref_id = cfg["builds"]["reference"]["id"]
    tgt_id = cfg["builds"]["target"]["id"]
    version = cfg["emit"]["mapping_version"]

    reporter.line("registry entries          : %d" % count)
    reporter.line("absent on %-16s: %d" % (tgt_id, missing))
    reporter.line("mapping version           : %s" % version)

    def emit_array(name, values):
        lines = ["constexpr uint32_t %s[kFcseAddrCount] = {" % name]
        for i in range(0, len(values), 8):
            chunk = values[i:i + 8]
            lines.append("    " + " ".join("0x%08X," % v for v in chunk))
        lines.append("};")
        return "\n".join(lines)

    header = """\
// Generated by tools/FCSE/tools/addrlib - do not edit by hand.
//
// Index is the address-library ID. IDs are dense and append-only, so the ID a
// plugin baked in resolves to the same function after any regeneration; see
// tools/FCSE/tools/addrlib/registry.csv for the authoritative list.
//
// mapping version : {version}
// generated       : {when}
// reference build : {ref_id} (IDs are minted against this build's RVAs)
// target build    : {tgt_id}
// entries         : {count}
// absent on target: {missing}
//
// kFcseRvaMissing means the ID has no counterpart in that build. Resolvers must
// treat it as a failure, never as an address.

#pragma once

#include <cstdint>

namespace FCSE {{

constexpr char     kFcseMappingVersion[] = "{version}";
constexpr uint32_t kFcseAddrCount = {count};
constexpr uint32_t kFcseRvaMissing = 0x{missing_val:08X};

// {ref_id}
{ref_array}

// {tgt_id}
{tgt_array}

}} // namespace FCSE
""".format(version=version, when=time.strftime("%Y-%m-%dT%H:%M:%S"),
           ref_id=ref_id, tgt_id=tgt_id, count=count, missing=missing,
           missing_val=MISSING,
           ref_array=emit_array("kFcseRva_" + ref_id, ref_col),
           tgt_array=emit_array("kFcseRva_" + tgt_id, tgt_col))

    dest = cfg["emit"]["table_header"]
    if not os.path.isabs(dest):
        dest = os.path.normpath(os.path.join(common.tool_dir(), dest))
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    tmp = dest + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(header)
    os.replace(tmp, dest)
    size_kb = os.path.getsize(dest) / 1024.0
    reporter.line("    -> %s (%.0f KiB)" % (dest, size_kb))

    tiers = defaultdict(int)
    for rva in ref_col:
        tiers[tier_of.get(rva, "absent")] += 1

    manifest = {
        "mapping_version": version,
        "generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "entries": count,
        "absent_on_target": missing,
        "tiers": dict(tiers),
        "config_sha256": cfg["_hash"],
        "builds": {},
    }
    for key in ("reference", "target"):
        spec = cfg["builds"][key]
        manifest["builds"][key] = {
            "id": spec["id"], "sha256": spec.get("sha256"),
            "size_of_image": spec.get("size_of_image"),
            "time_date_stamp": "0x%08X" % spec["time_date_stamp"],
        }
    common.write_json(os.path.join(out, "mapping_manifest.json"), manifest)
    reporter.line("    -> out/mapping_manifest.json")

    reporter.section("tier composition")
    for t in sorted(tiers, key=lambda t: -tiers[t]):
        reporter.line("    %-12s %d" % (t, tiers[t]))

    reporter.save(os.path.join(out, "emit_report.txt"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
