using System.Buffers.Binary;

namespace JackAll.Core.Format.Fcb;

/// <summary>
/// Reads and writes the Dunia .fcb binary object-tree format: compiled entity/weapon/vehicle/
/// world-sector definitions (research/knowledge.md §1-2, research/file_manifest.md §2).
/// </summary>
/// <remarks>
/// Ported directly from Gibbed's <c>BinaryResourceFile</c> (github.com/gibbed/Gibbed.Dunia, vendored
/// in this repo at tools/Gibbed.Dunia, FCB support last touched 2021) rather than shelling out to it
/// indefinitely: that project targets .NET Framework 4.8 and isn't being maintained for whatever this
/// tool ends up needing next, so its binary-tree algorithm is reproduced here as first-party,
/// actively maintained code instead. Verified byte-for-byte: a real .fcb generated by the vendored
/// Gibbed tool round-trips through this class's Deserialize -> Serialize unchanged, and every field
/// documented below was independently confirmed against the actual engine parser in Dunia.dll
/// (<c>Fcb_ReadHeader</c> @ 0x10235080, <c>Fcb_ParseObject</c> @ 0x10234d60, <c>Fcb_ReadTypeHash</c> @
/// 0x10234260 - see reverse/dunia/fcb_format.md) via GhidraMCP, not just inferred from the community
/// tool (JackAll.Core.Tests/FcbDocumentTests.cs).
///
/// Wire format: "FCbn"(4) + version=2(u16) + flags(u16, only bit 0 meaningful) + totalObjectCount(u32)
/// + totalValueCount(u32), then the root <see cref="FcbObject"/> tree. The two counts are written on
/// output but not relied on when reading: <c>totalObjectCount</c> does match the number of distinct
/// (backreference-deduplicated) objects exactly, confirmed against 5 real shipped .fcb files, but
/// <c>totalValueCount</c> does not match a simple "value slots across the unique object graph" tally
/// against those same files and what it precisely counts is still unresolved (see fcb_format.md) -
/// harmless to this class either way, since nothing here depends on it.
///
/// flags bit 0, when set, changes how TypeHash is read (confirmed in Fcb_ReadTypeHash): the leading
/// u32 becomes a fallback raw hash (used only if the string below turns out too long to hash), then a
/// second u32 gives a string length; if that length is under 512, that many bytes of a class-name
/// string follow and get hashed at load time instead of using the fallback. Every real .fcb sample
/// seen has flags == 0 (the plain u32 hash), so that alternate path is deliberately NOT implemented
/// here - Deserialize throws rather than silently mishandling it. Implement it if a real
/// flags-nonzero sample ever shows up.
///
/// Each object is: a "count" varint giving its child count, TypeHash, a "count" varint giving its
/// value count, then that many (nameHash(u32) + "count"-prefixed raw bytes) pairs, then that many
/// child objects recursively.
///
/// The "count" varint is genuinely dual-purpose at the object-child-list level, and shipped files
/// exploit it to deduplicate repeated data - a reader that didn't handle both tricks below would fail
/// on real game data, not just an edge case (Gibbed himself noted <c>entitylibrarypatchoverride.fcb</c>
/// is ~2.5 MiB on disk but balloons to ~11 MB once flattened to XML, i.e. real files lean on this
/// heavily):
/// - <b>Object-level</b>: when an object's child-list entry starts with the byte 0xFE, what follows
///   isn't a new object at all, but a 4-byte index into every object parsed so far in the file -
///   "reuse that whole subtree". Confirmed directly in Fcb_ParseObject's child loop.
/// - <b>Value-level</b>: 0xFE on a value's size field means the u32 that follows is a *backward byte
///   offset* from that field to an earlier value's own size field - "reuse those bytes". Confirmed
///   directly too: the engine's own tree-walk skips exactly 5 bytes here and never dereferences the
///   offset itself (it defers to whatever later reads that field's actual value on demand).
///
/// One place this class is deliberately *more* lenient than a naive reading of Gibbed's own code: a
/// count varint of exactly 0xFE means "backreference" only in the object-child-list position above.
/// An object's own child-count and value-count fields use the identical byte encoding (0xFE and 0xFF
/// both simply mean "read 4 more bytes for the literal") but never carry backreference meaning -
/// confirmed directly in Fcb_ParseObject, which branches on the marker byte identically for both
/// fields and never touches the backreference-lookup array there. See <see cref="ReadCount"/>.
///
/// Both dedup tricks are read-side only: this writer, like Gibbed's own, always emits the
/// fully-expanded form (plain byte counts, or 0xFF + u32 for anything >= 0xFE) - lossless, just
/// larger. That's why a round-trip test can expect byte-for-byte equality against a Gibbed-produced
/// fixture (neither writer ever produces the dedup'd form) but not necessarily against a real shipped
/// game file (which might).
/// </remarks>
public static class FcbDocument
{
    private const uint Signature = 0x4643626E; // "FCbn", little-endian
    private const ushort SupportedVersion = 2;
    private const byte OffsetMarker = 0xFE;
    private const byte LargeValueMarker = 0xFF;

    public static FcbObject Deserialize(byte[] fcb)
    {
        using var input = new MemoryStream(fcb, writable: false);
        ReadHeader(input);

        var pointers = new List<FcbObject>();
        return DeserializeObject(input, pointers);
    }

    /// <summary>
    /// Like <see cref="Deserialize"/>, but also reports each of the root's own direct children's exact
    /// on-disk byte span - captured for free while walking the stream this decode already has to do,
    /// rather than a second pass that re-serializes each child just to measure it (see
    /// <see cref="FcbXml.ListFragmentsWithSize"/>, the one consumer). This is the file's own raw
    /// size, dedup tricks and all (see class remarks): a child that happens to be an object-level
    /// backreference to an earlier subtree reports as little as 5 bytes - the marker and pointer it
    /// actually occupies here, not the size of whatever it points at. Deliberate: it's genuinely how
    /// many bytes of the shipped file that entry costs, same as <c>ReadHeader</c>'s bytes not counting
    /// toward the *next* file's size.
    /// </summary>
    public static (FcbObject Root, IReadOnlyList<long> ChildByteSizes) DeserializeWithChildSizes(byte[] fcb)
    {
        using var input = new MemoryStream(fcb, writable: false);
        ReadHeader(input);

        var pointers = new List<FcbObject>();
        var childByteSizes = new List<long>();
        FcbObject root = DeserializeObject(input, pointers, childByteSizes);
        return (root, childByteSizes);
    }

    private static void ReadHeader(MemoryStream input)
    {
        if (ReadU32(input) != Signature)
        {
            throw new InvalidDataException("Not an .fcb file (missing 'FCbn' signature).");
        }
        if (ReadU16(input) != SupportedVersion)
        {
            throw new InvalidDataException("Unsupported .fcb version (expected 2).");
        }
        if ((ReadU16(input) & 1) != 0)
        {
            throw new InvalidDataException(
                "Unsupported .fcb flags: bit 0 set means TypeHash is a hashed class-name string, " +
                "not a plain hash - not implemented (no real sample has been seen using it).");
        }

        ReadU32(input); // totalObjectCount - informational only
        ReadU32(input); // totalValueCount  - informational only
    }

    public static byte[] Serialize(FcbObject root)
    {
        using var body = new MemoryStream();
        uint totalObjectCount = 0, totalValueCount = 0;
        SerializeObject(root, body, ref totalObjectCount, ref totalValueCount);

        using var output = new MemoryStream();
        WriteU32(output, Signature);
        WriteU16(output, SupportedVersion);
        WriteU16(output, 0);
        WriteU32(output, totalObjectCount);
        WriteU32(output, totalValueCount);
        body.Position = 0;
        body.CopyTo(output);
        return output.ToArray();
    }

    /// <summary><paramref name="childByteSizes"/>, when given, collects the on-disk byte span of
    /// *this* object's own direct children only (not grandchildren - recursive calls below never pass
    /// it on), which is exactly what <see cref="DeserializeWithChildSizes"/> needs from its one call at
    /// the root.</summary>
    private static FcbObject DeserializeObject(MemoryStream input, List<FcbObject> pointers, List<long>? childByteSizes = null)
    {
        uint childCount = ReadCount(input, out bool isOffset);
        if (isOffset)
        {
            return pointers[(int)childCount];
        }

        var obj = new FcbObject();
        pointers.Add(obj);

        obj.TypeHash = ReadU32(input);

        // Unlike the child-list backreference above, an object's own value count never carries
        // backreference meaning - 0xFE and 0xFF are equivalent "read 4 more bytes" markers here (see
        // class remarks), so the isOffset flag is simply not meaningful for this particular read.
        uint valueCount = ReadCount(input, out _);

        for (int i = 0; i < valueCount; i++)
        {
            uint nameHash = ReadU32(input);
            obj.Values.Add(nameHash, ReadValueBytes(input));
        }

        for (int i = 0; i < childCount; i++)
        {
            long start = input.Position;
            obj.Children.Add(DeserializeObject(input, pointers));
            childByteSizes?.Add(input.Position - start);
        }

        return obj;
    }

    /// <summary>
    /// Reads one value's byte payload, following the backward-offset dedup trick (see class remarks)
    /// when the size field is marked as one.
    /// </summary>
    private static byte[] ReadValueBytes(MemoryStream input)
    {
        long sizeFieldPosition = input.Position;
        uint size = ReadCount(input, out bool isOffset);

        if (!isOffset)
        {
            byte[] direct = new byte[size];
            ReadExact(input, direct);
            return direct;
        }

        // 'size' is actually a backward byte offset to another value's own (always non-offset) size
        // field - jump there, read the real size and bytes, then return to just past this value's
        // own size field so the caller's stream position ends up in the right place either way.
        input.Position = sizeFieldPosition - size;
        uint realSize = ReadCount(input, out bool innerIsOffset);
        if (innerIsOffset)
        {
            throw new InvalidDataException("A shared value's own size field is itself a backreference.");
        }

        byte[] value = new byte[realSize];
        ReadExact(input, value);

        input.Position = sizeFieldPosition;
        ReadCount(input, out _); // re-consume this value's own size field to resume forward from here
        return value;
    }

    private static void SerializeObject(
        FcbObject obj, Stream output, ref uint totalObjectCount, ref uint totalValueCount)
    {
        totalObjectCount += (uint)obj.Children.Count;
        totalValueCount += (uint)obj.Values.Count;

        WriteCount(output, (uint)obj.Children.Count, isOffset: false);
        WriteU32(output, obj.TypeHash);

        WriteCount(output, (uint)obj.Values.Count, isOffset: false);
        foreach ((uint nameHash, byte[] value) in obj.Values)
        {
            WriteU32(output, nameHash);
            WriteCount(output, (uint)value.Length, isOffset: false);
            output.Write(value, 0, value.Length);
        }

        foreach (FcbObject child in obj.Children)
        {
            SerializeObject(child, output, ref totalObjectCount, ref totalValueCount);
        }
    }

    /// <summary>
    /// Decodes one "count" varint. <paramref name="isOffset"/> is only meaningful to the object-level
    /// child-list caller (see class remarks) - callers reading a plain count (an object's own child
    /// count or value count) should ignore it, since 0xFE and 0xFF decode identically there.
    /// </summary>
    private static uint ReadCount(Stream input, out bool isOffset)
    {
        byte marker = ReadU8(input);
        if (marker < OffsetMarker)
        {
            isOffset = false;
            return marker;
        }

        isOffset = marker == OffsetMarker;
        return ReadU32(input);
    }

    private static void WriteCount(Stream output, uint value, bool isOffset)
    {
        if (isOffset || value >= OffsetMarker)
        {
            WriteU8(output, isOffset ? OffsetMarker : LargeValueMarker);
            WriteU32(output, value);
            return;
        }

        WriteU8(output, (byte)value);
    }

    private static byte ReadU8(Stream input)
    {
        int b = input.ReadByte();
        if (b < 0)
        {
            throw new EndOfStreamException("Unexpected end of .fcb data.");
        }
        return (byte)b;
    }

    private static void WriteU8(Stream output, byte value) => output.WriteByte(value);

    private static ushort ReadU16(Stream input)
    {
        Span<byte> buffer = stackalloc byte[2];
        ReadExact(input, buffer);
        return BinaryPrimitives.ReadUInt16LittleEndian(buffer);
    }

    private static void WriteU16(Stream output, ushort value)
    {
        Span<byte> buffer = stackalloc byte[2];
        BinaryPrimitives.WriteUInt16LittleEndian(buffer, value);
        output.Write(buffer);
    }

    private static uint ReadU32(Stream input)
    {
        Span<byte> buffer = stackalloc byte[4];
        ReadExact(input, buffer);
        return BinaryPrimitives.ReadUInt32LittleEndian(buffer);
    }

    private static void WriteU32(Stream output, uint value)
    {
        Span<byte> buffer = stackalloc byte[4];
        BinaryPrimitives.WriteUInt32LittleEndian(buffer, value);
        output.Write(buffer);
    }

    private static void ReadExact(Stream input, Span<byte> buffer)
    {
        int total = 0;
        while (total < buffer.Length)
        {
            int read = input.Read(buffer[total..]);
            if (read == 0)
            {
                throw new EndOfStreamException("Unexpected end of .fcb data.");
            }
            total += read;
        }
    }
}
