using JackAll.Tools.Xbg;

namespace JackAll.Tools.Fc2Model;

/// <summary>A bone, or the pivot a rigid part is modelled on.</summary>
public sealed class MeshNode
{
    public required string Name { get; init; }

    public required uint Parent { get; init; }

    public required float[] Rotation { get; init; }

    public required float[] Translation { get; init; }

    public required float[] Scale { get; init; }

    public required int SkinIndex { get; init; }

    public required float Extent { get; init; }
}

/// <summary>One drawable block: which material it uses and which bones it may reference.</summary>
public sealed class MeshCluster
{
    public required ushort MaterialIndex { get; init; }

    public required ushort Flags { get; init; }

    public required short[] Palette { get; init; }
}

/// <summary>A named part, its fitted bounds, and the node that places it.</summary>
public sealed class MeshPart
{
    public required string Name { get; init; }

    public required float LodMetric { get; init; }

    public required float[] Bounds { get; init; }

    /// <summary>The node placing this part, or <see cref="XbgFile.NoPlacement"/> for the root's space.</summary>
    public required uint PlacementNode { get; init; }

    public List<MeshCluster> Clusters { get; init; } = [];
}

/// <summary>
/// One cluster's geometry, in float space and flat.
/// </summary>
/// <remarks>
/// Every component is one array with a fixed stride rather than a list of points, because that is
/// both what a <c>.bin</c> buffer holds and the only shape that survives a general serialiser -
/// a tuple's members are fields, so JSON writes each vertex as an empty object and loses the lot.
/// </remarks>
public sealed class MeshGeometry
{
    /// <summary>Weight and slot pairs per vertex, zero-padded to the wider of the two sets.</summary>
    public const int SkinStride = 8;

    public required uint Buffer { get; init; }

    public required uint Part { get; init; }

    public required uint Cluster { get; init; }

    public required int VertexCount { get; init; }

    /// <summary>Three per vertex.</summary>
    public required float[] Positions { get; init; }

    /// <summary>Two per vertex.</summary>
    public float[]? Uvs { get; init; }

    public float[]? Uvs1 { get; init; }

    /// <summary>Three per vertex.</summary>
    public float[]? Normals { get; init; }

    public float[]? Tangents { get; init; }

    public float[]? Binormals { get; init; }

    /// <summary>Four per vertex, RGBA.</summary>
    public float[]? Colours { get; init; }

    /// <summary><see cref="SkinStride"/> per vertex, alongside <see cref="SkinSlots"/>.</summary>
    public float[]? SkinWeights { get; init; }

    public int[]? SkinSlots { get; init; }

    public required int[] Indices { get; init; }
}

public sealed class MeshLod
{
    public required float Distance { get; init; }

    /// <summary>The vertex format each buffer uses, which decides what its components mean.</summary>
    public required List<uint> BufferFlags { get; init; }

    public List<MeshGeometry> Geometry { get; init; } = [];
}

/// <summary>A chunk the codec carries whole because nothing decodes it.</summary>
public sealed class MeshChunk
{
    public required string Tag { get; init; }

    public required byte[] Body { get; init; }
}

/// <summary>
/// A mesh with no Dunia bytes in it: names, transforms, bounds, palettes and float-space geometry.
/// </summary>
/// <remarks>
/// This is what a <c>.fc2model</c> carries instead of an <c>.xbg</c>, and what lets the editor that
/// opens one hold no format code at all. Everything the container derives from its own content is
/// left out and regenerated by <see cref="XbgFile.Derive"/> on the way back, so a model can gain a
/// part or an LOD rather than being transplanted into whatever a donor happened to have.
/// <para>
/// Two values survive because nothing derives them - <see cref="HeaderWord"/> and
/// <see cref="MaterialWord"/> - along with the bodies of chunks nothing decodes. The gate is that
/// every shipped mesh survives the trip: decode one to this and build it back, and the bytes
/// return.
/// </para>
/// </remarks>
public sealed class MeshDocument
{
    /// <summary>The vertex components this can express; a buffer using anything else is refused.</summary>
    public const uint SupportedComponents =
        XbgFile.PosInt16 | XbgFile.Uv0 | XbgFile.Uv1 | XbgFile.Normal
        | XbgFile.Colour | XbgFile.Tangent | XbgFile.Binormal | XbgFile.BoneWeights1;

    public required uint HeaderWord { get; init; }

    public required uint? MaterialWord { get; init; }

    public required List<string> Materials { get; init; }

    public required float[] Box { get; init; }

    public required float[] Sphere { get; init; }

    public required float[] PosCompress { get; init; }

    public required float[] UvCompress { get; init; }

    public List<MeshNode> Nodes { get; init; } = [];

    public List<float[]> BindMatrices { get; init; } = [];

    public List<MeshPart> Parts { get; init; } = [];

    public List<MeshLod> Lods { get; init; } = [];

    /// <summary>Which chunks the container holds and in what order, with any opaque bodies.</summary>
    public List<MeshChunk> Chunks { get; init; } = [];

    public static MeshDocument From(XbgFile file)
    {
        VertexScales scales = VertexScales.Of(file);
        var document = new MeshDocument
        {
            HeaderWord = file.HeaderWords[0],
            MaterialWord = file.MaterialWord,
            Materials = [.. file.Materials],
            Box = [.. file.Box],
            Sphere = [.. file.Sphere],
            PosCompress = [.. file.PosCompress],
            UvCompress = [.. file.UvCompress],
        };

        foreach (XbgNode node in file.Nodes)
        {
            document.Nodes.Add(new MeshNode
            {
                Name = node.Name,
                Parent = node.Parent,
                Rotation = [.. node.Rotation],
                Translation = [.. node.Translation],
                Scale = [.. node.Scale],
                SkinIndex = node.SkinIndex,
                Extent = node.Extent,
            });
        }

        foreach (float[] matrix in file.BindMatrices)
        {
            document.BindMatrices.Add([.. matrix]);
        }

        for (int index = 0; index < file.Parts.Count; index++)
        {
            XbgPart part = file.Parts[index];
            var fresh = new MeshPart
            {
                Name = part.Name,
                LodMetric = part.LodMetric,
                Bounds = [.. part.Bounds],
                PlacementNode = file.PartRefs[index].Node,
            };
            foreach (XbgCluster cluster in part.Clusters)
            {
                fresh.Clusters.Add(new MeshCluster
                {
                    MaterialIndex = cluster.MaterialIndex,
                    Flags = cluster.Flags,
                    Palette = [.. cluster.Palette],
                });
            }
            document.Parts.Add(fresh);
        }

        foreach (XbgLod lod in file.Lods)
        {
            var fresh = new MeshLod
            {
                Distance = lod.Distance,
                BufferFlags = [.. lod.VertexBuffers.Select(buffer => buffer.Flags)],
            };
            foreach (uint flags in fresh.BufferFlags)
            {
                Refuse(flags);
            }

            foreach (ClusterGeometry geometry in XbgGeometry.ReadLod(file, lod))
            {
                VertexStream stream = geometry.Vertices;
                (float[]? weights, int[]? slots) = FlattenSkin(stream.Skin());
                fresh.Geometry.Add(new MeshGeometry
                {
                    Buffer = geometry.Buffer,
                    Part = geometry.Part,
                    Cluster = geometry.Cluster,
                    VertexCount = stream.Count,
                    Positions = Flatten3(stream.Positions(file.PosScale)),
                    Uvs = Flatten2(stream.RawUvs(scales.UvTranslate, scales.UvScale, 0)),
                    Uvs1 = Flatten2(stream.RawUvs(scales.UvTranslate, scales.UvScale, 1)),
                    Normals = Flatten3(stream.Normals()),
                    Tangents = Flatten3(stream.Tangents()),
                    Binormals = Flatten3(stream.Binormals()),
                    Colours = Flatten4(stream.Colours()),
                    SkinWeights = weights,
                    SkinSlots = slots,
                    Indices = [.. geometry.Indices],
                });
            }
            document.Lods.Add(fresh);
        }

        foreach (XbgChunk chunk in file.Chunks)
        {
            document.Chunks.Add(new MeshChunk { Tag = chunk.Tag, Body = chunk.Raw });
        }
        return document;
    }

    /// <summary>Build the container back, deriving everything this deliberately does not carry.</summary>
    public XbgFile ToXbg()
    {
        var file = new XbgFile
        {
            HeaderWords = [HeaderWord, 0, 0, 0, 0],
            Materials = [.. Materials],
            MaterialWord = MaterialWord,
            Box = [.. Box],
            Sphere = [.. Sphere],
            PosCompress = [.. PosCompress],
            UvCompress = [.. UvCompress],
        };

        foreach (MeshNode node in Nodes)
        {
            file.Nodes.Add(new XbgNode
            {
                Name = node.Name,
                Parent = node.Parent,
                Rotation = [.. node.Rotation],
                Translation = [.. node.Translation],
                Scale = [.. node.Scale],
                SkinIndex = node.SkinIndex,
                Extent = node.Extent,
                NameHash = 0,
                FirstChild = 0,
                NextSibling = 0,
                Weight = 0.0f,
            });
        }

        foreach (float[] matrix in BindMatrices)
        {
            file.BindMatrices.Add([.. matrix]);
        }

        foreach (MeshPart part in Parts)
        {
            var fresh = new XbgPart
            {
                Name = part.Name,
                LodMetric = part.LodMetric,
                Bounds = [.. part.Bounds],
                Lod = 0,
                Reserved = 0,
            };
            foreach (MeshCluster cluster in part.Clusters)
            {
                fresh.Clusters.Add(new XbgCluster
                {
                    MaterialIndex = cluster.MaterialIndex,
                    Flags = cluster.Flags,
                    Palette = [.. cluster.Palette],
                    FaceCount = 0,
                    Stride = 0,
                    VertexCount = 0,
                });
            }
            file.Parts.Add(fresh);
            file.PartRefs.Add(new XbgPartRef { NameHash = 0, Node = part.PlacementNode });
        }

        foreach (MeshLod lod in Lods)
        {
            file.Lods.Add(new XbgLod
            {
                Distance = lod.Distance,
                VertexBuffers = [.. lod.BufferFlags.Select(flags => new XbgVertexBuffer
                {
                    Flags = flags,
                    Stride = (uint)XbgFile.VertexLayout(flags).Stride,
                    VertexCount = 0,
                    Offset = 0,
                })],
                Submeshes = [.. lod.Geometry.Select(g => new XbgSubmeshRef
                {
                    Buffer = g.Buffer,
                    Part = g.Part,
                    Cluster = g.Cluster,
                    IndexOffset = 0,
                    Trailing = [0, 0, 0],
                })],
                VertexData = [],
                IndexData = [],
            });
        }

        foreach (MeshChunk chunk in Chunks)
        {
            file.Chunks.Add(new XbgChunk { Tag = chunk.Tag, Word0 = 0, Raw = chunk.Body });
        }

        file.Derive();

        VertexScales scales = VertexScales.Of(file);
        foreach ((MeshLod lod, XbgLod target) in Lods.Zip(file.Lods))
        {
            List<ClusterGeometry> geometries = [.. lod.Geometry.Select((g, position) => new ClusterGeometry
            {
                Submesh = position,
                Buffer = g.Buffer,
                Part = g.Part,
                Cluster = g.Cluster,
                Vertices = VertexEncoder.Encode(
                    lod.BufferFlags[(int)g.Buffer], g.VertexCount, scales, VerticesOf(g)),
                Indices = [.. g.Indices],
            })];
            XbgGeometry.WriteLod(file, target, geometries);
        }
        return file;
    }

    private static VertexData VerticesOf(MeshGeometry geometry) => new()
    {
        Positions = Unflatten3(geometry.Positions),
        Uvs = Unflatten2(geometry.Uvs),
        Uvs1 = Unflatten2(geometry.Uvs1),
        Normals = Unflatten3(geometry.Normals),
        Tangents = Unflatten3(geometry.Tangents),
        Binormals = Unflatten3(geometry.Binormals),
        Colours = Unflatten4(geometry.Colours),
        Skin = UnflattenSkin(geometry.SkinWeights, geometry.SkinSlots),
    };

    private static float[]? Flatten2((float U, float V)[]? values)
        => values is null ? null : [.. values.SelectMany(v => (float[])[v.U, v.V])];

    private static float[]? Flatten3((float X, float Y, float Z)[]? values)
        => values is null ? null : [.. values.SelectMany(v => (float[])[v.X, v.Y, v.Z])];

    private static float[]? Flatten4((float R, float G, float B, float A)[]? values)
        => values is null ? null : [.. values.SelectMany(v => (float[])[v.R, v.G, v.B, v.A])];

    /// <summary>Zero-weight pairs are dropped on decode, so they are padded back in here.</summary>
    private static (float[]? Weights, int[]? Slots) FlattenSkin(List<(float Weight, int Slot)>[]? skin)
    {
        if (skin is null)
        {
            return (null, null);
        }

        var weights = new float[skin.Length * MeshGeometry.SkinStride];
        var slots = new int[skin.Length * MeshGeometry.SkinStride];
        for (int vertex = 0; vertex < skin.Length; vertex++)
        {
            for (int at = 0; at < skin[vertex].Count && at < MeshGeometry.SkinStride; at++)
            {
                weights[(vertex * MeshGeometry.SkinStride) + at] = skin[vertex][at].Weight;
                slots[(vertex * MeshGeometry.SkinStride) + at] = skin[vertex][at].Slot;
            }
        }
        return (weights, slots);
    }

    private static (float U, float V)[]? Unflatten2(float[]? flat)
        => flat is null ? null : [.. Enumerable.Range(0, flat.Length / 2).Select(i => (flat[i * 2], flat[(i * 2) + 1]))];

    private static (float X, float Y, float Z)[]? Unflatten3(float[]? flat)
        => flat is null
            ? null
            : [.. Enumerable.Range(0, flat.Length / 3)
                .Select(i => (flat[i * 3], flat[(i * 3) + 1], flat[(i * 3) + 2]))];

    private static (float R, float G, float B, float A)[]? Unflatten4(float[]? flat)
        => flat is null
            ? null
            : [.. Enumerable.Range(0, flat.Length / 4)
                .Select(i => (flat[i * 4], flat[(i * 4) + 1], flat[(i * 4) + 2], flat[(i * 4) + 3]))];

    private static List<(float Weight, int Slot)>[]? UnflattenSkin(float[]? weights, int[]? slots)
    {
        if (weights is null || slots is null)
        {
            return null;
        }

        var skin = new List<(float, int)>[weights.Length / MeshGeometry.SkinStride];
        for (int vertex = 0; vertex < skin.Length; vertex++)
        {
            List<(float, int)> pairs = [];
            for (int at = 0; at < MeshGeometry.SkinStride; at++)
            {
                float weight = weights[(vertex * MeshGeometry.SkinStride) + at];
                if (weight != 0.0f)
                {
                    pairs.Add((weight, slots[(vertex * MeshGeometry.SkinStride) + at]));
                }
            }
            skin[vertex] = pairs;
        }
        return skin;
    }

    private static void Refuse(uint flags)
    {
        uint unsupported = flags & ~SupportedComponents;
        if (unsupported != 0)
        {
            throw new NotSupportedException(
                $"Vertex format 0x{flags:X} uses components this cannot carry (0x{unsupported:X}). "
                + "No shipped mesh does, so this is a format the decoder has never seen.");
        }
    }
}
