using System.Text;

namespace JackAll.Tools.Reach;

public sealed record GroundTruth(string Name, bool Pass, string Detail);

/// <summary>
/// Renders a <see cref="ReachResult"/>: the TSV asset, the decoy ranking, and the ground-truth
/// checks that gate whether a run is trustworthy enough to check in.
/// </summary>
public static class ReachReport
{
    public static string VerdictText(ReachVerdict verdict) => verdict switch
    {
        ReachVerdict.Used => "used",
        ReachVerdict.UsedSpOnly => "used-sp-only",
        ReachVerdict.UsedMpOnly => "used-mp-only",
        ReachVerdict.Unused => "unused",
        _ => "unknown",
    };

    public static void WriteTsv(string path, IReadOnlyList<ReachRow> rows)
    {
        var text = new StringBuilder(rows.Count * 96);
        text.AppendLine("# fc2.reach.tsv - corpus reachability verdicts. Generated by `jackall-cli xref reach`;");
        text.AppendLine("# do not hand-edit. Methodology: docs/docs/engine-internals/asset-reachability.md");
        text.AppendLine("# hash\tpath\tverdict\tflags\tbytes\toutRefs\treason");
        foreach (ReachRow row in rows)
        {
            text.Append(row.File.Hash.ToString("X8")).Append('\t')
                .Append(row.File.Path).Append('\t')
                .Append(VerdictText(row.Verdict)).Append('\t')
                .Append(row.Flags.Render()).Append('\t')
                .Append(row.File.Size).Append('\t')
                .Append(row.OutRefs).Append('\t')
                .AppendLine(row.Reason);
        }
        File.WriteAllText(path, text.ToString());
    }

    /// <summary>The files this analysis exists to expose: unused, but shaped like something the
    /// game depends on. Ranked worst-first.</summary>
    public static IReadOnlyList<ReachRow> Decoys(IReadOnlyList<ReachRow> rows)
        => [.. rows
            .Where(r => r.Flags.HasFlag(ReachFlags.Decoy))
            .OrderByDescending(r => r.OutRefs)
            .ThenByDescending(r => r.File.Size)];

    /// <summary>
    /// Everything the docs already know to be dead or platform-bound, checked against this run.
    /// A failing entry means the analysis (usually its roots or policy) is wrong, not the docs.
    /// </summary>
    public static List<GroundTruth> CheckGroundTruths(IReadOnlyList<ReachRow> rows)
    {
        var truths = new List<GroundTruth>();

        void Check(string name, IEnumerable<ReachRow> subject, Func<ReachRow, bool> ok, bool emptyIsFailure = true)
        {
            var all = subject.ToList();
            var violations = all.Where(r => !ok(r)).ToList();
            bool pass = violations.Count == 0 && (!emptyIsFailure || all.Count > 0);
            string detail = all.Count == 0
                ? "no matching rows"
                : violations.Count == 0
                    ? $"{all.Count} row(s) ok"
                    : $"{violations.Count}/{all.Count} violate, e.g. {violations[0].File.Path} = {VerdictText(violations[0].Verdict)} ({violations[0].Reason})";
            truths.Add(new GroundTruth(name, pass, detail));
        }

        static bool IsUsed(ReachRow r) => r.Verdict is ReachVerdict.Used or ReachVerdict.UsedSpOnly or ReachVerdict.UsedMpOnly;

        Check("authoring-twins-unused",
            rows.Where(r => r.File.Path.EndsWith(@"\movemgrnamed.bin", StringComparison.OrdinalIgnoreCase)
                         || r.File.Path.EndsWith(@"\dlc1named.bin", StringComparison.OrdinalIgnoreCase)),
            r => r.Verdict == ReachVerdict.Unused && r.Flags.HasFlag(ReachFlags.Decoy));

        Check("debug-lua-unused",
            rows.Where(r => r.File.Path.EndsWith(".debug.lua", StringComparison.OrdinalIgnoreCase)),
            r => r.Verdict == ReachVerdict.Unused);

        Check("depload-twins-fallback",
            rows.Where(r => r.File.Path.StartsWith(@"worlds\", StringComparison.OrdinalIgnoreCase)
                         && r.File.Path.EndsWith("_depload.xml", StringComparison.OrdinalIgnoreCase)),
            r => r.Verdict == ReachVerdict.Unused
                 && r.Reason.StartsWith("fallback", StringComparison.Ordinal)
                 && r.Flags.HasFlag(ReachFlags.Decoy));

        Check("entitylibrary-full-not-sp",
            rows.Where(r => r.File.Path.EndsWith(@"\entitylibrary_full.fcb", StringComparison.OrdinalIgnoreCase)),
            r => !r.Flags.HasFlag(ReachFlags.SP));

        Check("console-leftovers-unused",
            rows.Where(r => ReachPolicy.IsConsoleOnly(r.File.Path)),
            r => r.Verdict == ReachVerdict.Unused && r.Reason == "console-only");

        Check("shadersobj-used",
            rows.Where(r => string.Equals(r.File.SourceName, "shadersobj", StringComparison.OrdinalIgnoreCase)),
            r => r.Verdict == ReachVerdict.Used);

        Check("movemgr-used",
            rows.Where(r => string.Equals(r.File.Path, @"graphics\move\movemgr.bin", StringComparison.OrdinalIgnoreCase)),
            IsUsed);

        Check("alwaysloaded-used",
            rows.Where(r => string.Equals(r.File.Path, @"config\alwaysloaded.xml", StringComparison.OrdinalIgnoreCase)),
            IsUsed);

        Check("sound-dirs-used",
            rows.Where(r => r.File.SourceName is "sound" or "sound_english"),
            IsUsed);

        Check("collision-never-unused",
            rows.Where(r => ReachPolicy.KnownCollisions.ContainsKey(r.File.Hash)),
            r => r.Verdict != ReachVerdict.Unused && r.Reason.StartsWith("collision:", StringComparison.Ordinal));

        Check("unnamed-never-unused",
            rows.Where(r => !r.File.NameIsKnown),
            r => r.Verdict != ReachVerdict.Unused);

        Check("tmpla-never-used",
            rows.Where(r => r.File.Path.StartsWith(@"worlds\tmpla\", StringComparison.OrdinalIgnoreCase)
                         || r.File.Path.StartsWith(@"levels\tmpla\", StringComparison.OrdinalIgnoreCase)),
            r => !IsUsed(r));

        Check("qa-scripts-unused",
            rows.Where(r => r.File.Path.Contains(@"\gyms\", StringComparison.OrdinalIgnoreCase)
                         || r.File.Path.Contains(@"\debugboxes\", StringComparison.OrdinalIgnoreCase)
                         || System.IO.Path.GetFileName(r.File.Path).StartsWith("ubidays.", StringComparison.OrdinalIgnoreCase)),
            r => !IsUsed(r));

        // Every _mip0 sibling must carry at least its base texture's flags - the embedded-path
        // edge is the only thing that can reach it.
        var byPath = rows.ToDictionary(r => r.File.Path, StringComparer.OrdinalIgnoreCase);
        Check("mip0-inherits-base-flags",
            rows.Where(r => r.File.NameIsKnown && r.File.Path.EndsWith("_mip0.xbt", StringComparison.OrdinalIgnoreCase)),
            r => !byPath.TryGetValue(r.File.Path[..^"_mip0.xbt".Length] + ".xbt", out ReachRow? baseRow)
                 || (r.Flags.Modes() & baseRow.Flags.Modes()) == baseRow.Flags.Modes());

        return truths;
    }
}
